// FspiopProfiles.mo: GENERATED by tools/fspiop/profile_gen.py from the official OpenAPI snippets
// (mojaloop/api-snippets 18.4.1, commit 226cf89f3d43, fspiop/v1_1/openapi3). Do not edit: regenerate.
//
// 46 operations on 30 paths; 80 schemas reached from their
// request bodies. FspiopSchema.mo validates a body against `schema(name)`; FspiopCore.mo routes a request
// by `OPERATIONS`.

module {
  public type Schema = {
    #object_ : { properties : [(Text, Schema)]; required : [Text] };
    #array_ : { items : Schema; minItems : ?Nat; maxItems : ?Nat };
    #string : { pattern : ?Text; enum_ : ?[Text]; minLength : ?Nat; maxLength : ?Nat };
    #integer : { minimum : ?Int; maximum : ?Int };
    #number;
    #boolean;
    #ref : Text;
    #anyOf : { alternatives : [Schema]; pattern : ?Text };
    #allOf : { alternatives : [Schema]; pattern : ?Text };
    #oneOf : { alternatives : [Schema]; pattern : ?Text };
  };
  public type Operation = { method : Text; path : Text; operationId : Text; request : ?Text; responses : [Nat] };

  public let SOURCE = { package = "mojaloop/api-snippets"; version = "18.4.1"; commit = "226cf89f3d43d29fb52f087d2772372bea88014d"; api = "fspiop/v1_1/openapi3" };

  public let OPERATIONS : [Operation] = [
    { method = "GET"; path = "/participants/{Type}/{ID}"; operationId = "ParticipantsByTypeAndID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/participants/{Type}/{ID}"; operationId = "ParticipantsByIDAndType"; request = ?"ParticipantsTypeIDSubIDPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/participants/{Type}/{ID}"; operationId = "ParticipantsByTypeAndID3"; request = ?"ParticipantsTypeIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "DELETE"; path = "/participants/{Type}/{ID}"; operationId = "ParticipantsByTypeAndID2"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/participants/{Type}/{ID}/error"; operationId = "ParticipantsErrorByTypeAndID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/participants/{Type}/{ID}/{SubId}"; operationId = "ParticipantsSubIdByTypeAndID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/participants/{Type}/{ID}/{SubId}"; operationId = "ParticipantsSubIdByTypeAndIDPost"; request = ?"ParticipantsTypeIDSubIDPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/participants/{Type}/{ID}/{SubId}"; operationId = "ParticipantsSubIdByTypeAndID3"; request = ?"ParticipantsTypeIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "DELETE"; path = "/participants/{Type}/{ID}/{SubId}"; operationId = "ParticipantsSubIdByTypeAndID2"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/participants/{Type}/{ID}/{SubId}/error"; operationId = "ParticipantsSubIdErrorByTypeAndID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/participants"; operationId = "Participants1"; request = ?"ParticipantsPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/participants/{ID}"; operationId = "putParticipantsByID"; request = ?"ParticipantsIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/participants/{ID}/error"; operationId = "ParticipantsByIDAndError"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/parties/{Type}/{ID}"; operationId = "PartiesByTypeAndID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/parties/{Type}/{ID}"; operationId = "PartiesByTypeAndID2"; request = ?"PartiesTypeIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/parties/{Type}/{ID}/error"; operationId = "PartiesErrorByTypeAndID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/parties/{Type}/{ID}/{SubId}"; operationId = "PartiesSubIdByTypeAndID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/parties/{Type}/{ID}/{SubId}"; operationId = "PartiesSubIdByTypeAndIDPut"; request = ?"PartiesTypeIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/parties/{Type}/{ID}/{SubId}/error"; operationId = "PartiesSubIdErrorByTypeAndID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/transactionRequests"; operationId = "TransactionRequests"; request = ?"TransactionRequestsPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/transactionRequests/{ID}"; operationId = "TransactionRequestsByID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/transactionRequests/{ID}"; operationId = "TransactionRequestsByIDPut"; request = ?"TransactionRequestsIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/transactionRequests/{ID}/error"; operationId = "TransactionRequestsErrorByID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/quotes"; operationId = "Quotes"; request = ?"QuotesPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/quotes/{ID}"; operationId = "QuotesByID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/quotes/{ID}"; operationId = "QuotesByID1"; request = ?"QuotesIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/quotes/{ID}/error"; operationId = "QuotesByIDAndError"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/authorizations/{ID}"; operationId = "AuthorizationsByIDGet"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/authorizations/{ID}"; operationId = "AuthorizationsByIDPut"; request = ?"AuthorizationsIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/authorizations/{ID}/error"; operationId = "AuthorizationsByIDAndError"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/transfers"; operationId = "transfers"; request = ?"TransfersPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/transfers/{ID}"; operationId = "TransfersByIDGet"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/transfers/{ID}"; operationId = "TransfersByIDPut"; request = ?"TransfersIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PATCH"; path = "/transfers/{ID}"; operationId = "TransfersByIDPatch"; request = ?"TransfersIDPatchResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/transfers/{ID}/error"; operationId = "TransfersByIDAndError"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/transactions/{ID}"; operationId = "TransactionsByID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/transactions/{ID}"; operationId = "TransactionsByID1"; request = ?"TransactionsIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/transactions/{ID}/error"; operationId = "TransactionsErrorByID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/bulkQuotes"; operationId = "BulkQuotes"; request = ?"BulkQuotesPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/bulkQuotes/{ID}"; operationId = "BulkQuotesByID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/bulkQuotes/{ID}"; operationId = "BulkQuotesByID1"; request = ?"BulkQuotesIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/bulkQuotes/{ID}/error"; operationId = "BulkQuotesErrorByID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "POST"; path = "/bulkTransfers"; operationId = "BulkTransfers"; request = ?"BulkTransfersPostRequest"; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "GET"; path = "/bulkTransfers/{ID}"; operationId = "BulkTransferByID"; request = null; responses = [202, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/bulkTransfers/{ID}"; operationId = "BulkTransfersByIDPut"; request = ?"BulkTransfersIDPutResponse"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
    { method = "PUT"; path = "/bulkTransfers/{ID}/error"; operationId = "BulkTransfersErrorByID"; request = ?"ErrorInformationObject"; responses = [200, 400, 401, 403, 404, 405, 406, 501, 503] },
  ];

  public let SCHEMAS : [(Text, Schema)] = [
    ("Amount", #string({ pattern = ?"^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[1-9])?$"; enum_ = null; minLength = null; maxLength = null })),
    ("AmountType", #string({ pattern = null; enum_ = ?["SEND", "RECEIVE"]; minLength = null; maxLength = null })),
    ("AuthenticationInfo", #object_({ properties = [("authentication", #ref("AuthenticationType")), ("authenticationValue", #ref("AuthenticationValue"))]; required = ["authentication", "authenticationValue"] })),
    ("AuthenticationType", #string({ pattern = null; enum_ = ?["OTP", "QRCODE", "U2F"]; minLength = null; maxLength = null })),
    ("AuthenticationValue", #anyOf({ alternatives = [#ref("OtpValue"), #ref("QRCODE"), #ref("U2FPinValue")]; pattern = ?"^\\d{3,10}$|^\\S{1,64}$" })),
    ("AuthorizationResponse", #string({ pattern = null; enum_ = ?["ENTERED", "REJECTED", "RESEND"]; minLength = null; maxLength = null })),
    ("AuthorizationsIDPutResponse", #object_({ properties = [("authenticationInfo", #ref("AuthenticationInfo")), ("responseType", #ref("AuthorizationResponse"))]; required = ["responseType"] })),
    ("BalanceOfPayments", #string({ pattern = ?"^[1-9]\\d{2}$"; enum_ = null; minLength = null; maxLength = null })),
    ("BulkQuotesIDPutResponse", #object_({ properties = [("individualQuoteResults", #array_({ items = #ref("IndividualQuoteResult"); minItems = null; maxItems = ?1000 })), ("expiration", #ref("DateTime")), ("extensionList", #ref("ExtensionList"))]; required = ["expiration"] })),
    ("BulkQuotesPostRequest", #object_({ properties = [("bulkQuoteId", #ref("CorrelationId")), ("payer", #ref("Party")), ("geoCode", #ref("GeoCode")), ("expiration", #ref("DateTime")), ("individualQuotes", #array_({ items = #ref("IndividualQuote"); minItems = ?1; maxItems = ?1000 })), ("extensionList", #ref("ExtensionList"))]; required = ["bulkQuoteId", "payer", "individualQuotes"] })),
    ("BulkTransferState", #string({ pattern = null; enum_ = ?["RECEIVED", "PENDING", "ACCEPTED", "PROCESSING", "COMPLETED", "REJECTED"]; minLength = null; maxLength = null })),
    ("BulkTransfersIDPutResponse", #object_({ properties = [("completedTimestamp", #ref("DateTime")), ("individualTransferResults", #array_({ items = #ref("IndividualTransferResult"); minItems = null; maxItems = ?1000 })), ("bulkTransferState", #ref("BulkTransferState")), ("extensionList", #ref("ExtensionList"))]; required = ["bulkTransferState"] })),
    ("BulkTransfersPostRequest", #object_({ properties = [("bulkTransferId", #ref("CorrelationId")), ("bulkQuoteId", #ref("CorrelationId")), ("payerFsp", #ref("FspId")), ("payeeFsp", #ref("FspId")), ("individualTransfers", #array_({ items = #ref("IndividualTransfer"); minItems = ?1; maxItems = ?1000 })), ("expiration", #ref("DateTime")), ("extensionList", #ref("ExtensionList"))]; required = ["bulkTransferId", "bulkQuoteId", "payerFsp", "payeeFsp", "individualTransfers", "expiration"] })),
    ("Code", #string({ pattern = ?"^[0-9a-zA-Z]{4,32}$"; enum_ = null; minLength = null; maxLength = null })),
    ("CorrelationId", #string({ pattern = ?"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"; enum_ = null; minLength = null; maxLength = null })),
    ("Currency", #string({ pattern = null; enum_ = ?["AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRO", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SPL", "SRD", "STD", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TVD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VEF", "VND", "VUV", "WST", "XAF", "XCD", "XDR", "XOF", "XPF", "XTS", "XXX", "YER", "ZAR", "ZMW", "ZWD"]; minLength = ?3; maxLength = ?3 })),
    ("DateOfBirth", #string({ pattern = ?"^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$"; enum_ = null; minLength = null; maxLength = null })),
    ("DateTime", #string({ pattern = ?"^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:(\\.\\d{3}))(?:Z|[+-][01]\\d:[0-5]\\d)$"; enum_ = null; minLength = null; maxLength = null })),
    ("ErrorCode", #string({ pattern = ?"^[1-9]\\d{3}$"; enum_ = null; minLength = null; maxLength = null })),
    ("ErrorDescription", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("ErrorInformation", #object_({ properties = [("errorCode", #ref("ErrorCode")), ("errorDescription", #ref("ErrorDescription")), ("extensionList", #ref("ExtensionList"))]; required = ["errorCode", "errorDescription"] })),
    ("ErrorInformationObject", #object_({ properties = [("errorInformation", #ref("ErrorInformation"))]; required = ["errorInformation"] })),
    ("Extension", #object_({ properties = [("key", #ref("ExtensionKey")), ("value", #ref("ExtensionValue"))]; required = ["key", "value"] })),
    ("ExtensionKey", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?32 })),
    ("ExtensionList", #object_({ properties = [("extension", #array_({ items = #ref("Extension"); minItems = ?1; maxItems = ?16 }))]; required = ["extension"] })),
    ("ExtensionValue", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("FirstName", #string({ pattern = ?"^(?!\\s*$)[\\p{L}\\p{gc=Mark}\\p{digit}\\p{gc=Connector_Punctuation}\\p{Join_Control} .,''-]{1,128}$"; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("FspId", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?32 })),
    ("GeoCode", #object_({ properties = [("latitude", #ref("Latitude")), ("longitude", #ref("Longitude"))]; required = ["latitude", "longitude"] })),
    ("IlpCondition", #string({ pattern = ?"^[A-Za-z0-9-_]{43}$"; enum_ = null; minLength = null; maxLength = ?48 })),
    ("IlpFulfilment", #string({ pattern = ?"^[A-Za-z0-9-_]{43}$"; enum_ = null; minLength = null; maxLength = ?48 })),
    ("IlpPacket", #string({ pattern = ?"^[A-Za-z0-9-_]+[=]{0,2}$"; enum_ = null; minLength = ?1; maxLength = ?32768 })),
    ("IndividualQuote", #object_({ properties = [("quoteId", #ref("CorrelationId")), ("transactionId", #ref("CorrelationId")), ("payee", #ref("Party")), ("amountType", #ref("AmountType")), ("amount", #ref("Money")), ("fees", #ref("Money")), ("transactionType", #ref("TransactionType")), ("note", #ref("Note")), ("extensionList", #ref("ExtensionList"))]; required = ["quoteId", "transactionId", "payee", "amountType", "amount", "transactionType"] })),
    ("IndividualQuoteResult", #object_({ properties = [("quoteId", #ref("CorrelationId")), ("payee", #ref("Party")), ("transferAmount", #ref("Money")), ("payeeReceiveAmount", #ref("Money")), ("payeeFspFee", #ref("Money")), ("payeeFspCommission", #ref("Money")), ("ilpPacket", #ref("IlpPacket")), ("condition", #ref("IlpCondition")), ("errorInformation", #ref("ErrorInformation")), ("extensionList", #ref("ExtensionList"))]; required = ["quoteId"] })),
    ("IndividualTransfer", #object_({ properties = [("transferId", #ref("CorrelationId")), ("transferAmount", #ref("Money")), ("ilpPacket", #ref("IlpPacket")), ("condition", #ref("IlpCondition")), ("extensionList", #ref("ExtensionList"))]; required = ["transferId", "transferAmount", "ilpPacket", "condition"] })),
    ("IndividualTransferResult", #object_({ properties = [("transferId", #ref("CorrelationId")), ("fulfilment", #ref("IlpFulfilment")), ("errorInformation", #ref("ErrorInformation")), ("extensionList", #ref("ExtensionList"))]; required = ["transferId"] })),
    ("Integer", #string({ pattern = ?"^[1-9]\\d*$"; enum_ = null; minLength = null; maxLength = null })),
    ("LastName", #string({ pattern = ?"^(?!\\s*$)[\\p{L}\\p{gc=Mark}\\p{digit}\\p{gc=Connector_Punctuation}\\p{Join_Control} .,''-]{1,128}$"; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("Latitude", #string({ pattern = ?"^(\\+|-)?(?:90(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,6})?))$"; enum_ = null; minLength = null; maxLength = null })),
    ("Longitude", #string({ pattern = ?"^(\\+|-)?(?:180(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,6})?))$"; enum_ = null; minLength = null; maxLength = null })),
    ("MerchantClassificationCode", #string({ pattern = ?"^[\\d]{1,4}$"; enum_ = null; minLength = null; maxLength = null })),
    ("MiddleName", #string({ pattern = ?"^(?!\\s*$)[\\p{L}\\p{gc=Mark}\\p{digit}\\p{gc=Connector_Punctuation}\\p{Join_Control} .,''-]{1,128}$"; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("Money", #object_({ properties = [("currency", #ref("Currency")), ("amount", #ref("Amount"))]; required = ["currency", "amount"] })),
    ("Note", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("OtpValue", #string({ pattern = ?"^\\d{3,10}$"; enum_ = null; minLength = null; maxLength = null })),
    ("ParticipantsIDPutResponse", #object_({ properties = [("partyList", #array_({ items = #ref("PartyResult"); minItems = ?1; maxItems = ?10000 })), ("currency", #ref("Currency"))]; required = ["partyList"] })),
    ("ParticipantsPostRequest", #object_({ properties = [("requestId", #ref("CorrelationId")), ("partyList", #array_({ items = #ref("PartyIdInfo"); minItems = ?1; maxItems = ?10000 })), ("currency", #ref("Currency"))]; required = ["requestId", "partyList"] })),
    ("ParticipantsTypeIDPutResponse", #object_({ properties = [("fspId", #ref("FspId"))]; required = [] })),
    ("ParticipantsTypeIDSubIDPostRequest", #object_({ properties = [("fspId", #ref("FspId")), ("currency", #ref("Currency")), ("extensionList", #ref("ExtensionList"))]; required = ["fspId"] })),
    ("PartiesTypeIDPutResponse", #object_({ properties = [("party", #ref("Party"))]; required = ["party"] })),
    ("Party", #object_({ properties = [("partyIdInfo", #ref("PartyIdInfo")), ("merchantClassificationCode", #ref("MerchantClassificationCode")), ("name", #ref("PartyName")), ("personalInfo", #ref("PartyPersonalInfo"))]; required = ["partyIdInfo"] })),
    ("PartyComplexName", #object_({ properties = [("firstName", #ref("FirstName")), ("middleName", #ref("MiddleName")), ("lastName", #ref("LastName"))]; required = [] })),
    ("PartyIdInfo", #object_({ properties = [("partyIdType", #ref("PartyIdType")), ("partyIdentifier", #ref("PartyIdentifier")), ("partySubIdOrType", #ref("PartySubIdOrType")), ("fspId", #ref("FspId")), ("extensionList", #ref("ExtensionList"))]; required = ["partyIdType", "partyIdentifier"] })),
    ("PartyIdType", #string({ pattern = null; enum_ = ?["MSISDN", "EMAIL", "PERSONAL_ID", "BUSINESS", "DEVICE", "ACCOUNT_ID", "IBAN", "ALIAS"]; minLength = null; maxLength = null })),
    ("PartyIdentifier", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("PartyName", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("PartyPersonalInfo", #object_({ properties = [("complexName", #ref("PartyComplexName")), ("dateOfBirth", #ref("DateOfBirth"))]; required = [] })),
    ("PartyResult", #object_({ properties = [("partyId", #ref("PartyIdInfo")), ("errorInformation", #ref("ErrorInformation"))]; required = ["partyId"] })),
    ("PartySubIdOrType", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("QRCODE", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?64 })),
    ("QuotesIDPutResponse", #object_({ properties = [("transferAmount", #ref("Money")), ("payeeReceiveAmount", #ref("Money")), ("payeeFspFee", #ref("Money")), ("payeeFspCommission", #ref("Money")), ("expiration", #ref("DateTime")), ("geoCode", #ref("GeoCode")), ("ilpPacket", #ref("IlpPacket")), ("condition", #ref("IlpCondition")), ("extensionList", #ref("ExtensionList"))]; required = ["transferAmount", "expiration", "ilpPacket", "condition"] })),
    ("QuotesPostRequest", #object_({ properties = [("quoteId", #ref("CorrelationId")), ("transactionId", #ref("CorrelationId")), ("transactionRequestId", #ref("CorrelationId")), ("payee", #ref("Party")), ("payer", #ref("Party")), ("amountType", #ref("AmountType")), ("amount", #ref("Money")), ("fees", #ref("Money")), ("transactionType", #ref("TransactionType")), ("geoCode", #ref("GeoCode")), ("note", #ref("Note")), ("expiration", #ref("DateTime")), ("extensionList", #ref("ExtensionList"))]; required = ["quoteId", "transactionId", "payee", "payer", "amountType", "amount", "transactionType"] })),
    ("Refund", #object_({ properties = [("originalTransactionId", #ref("CorrelationId")), ("refundReason", #ref("RefundReason"))]; required = ["originalTransactionId"] })),
    ("RefundReason", #string({ pattern = null; enum_ = null; minLength = ?1; maxLength = ?128 })),
    ("TransactionInitiator", #string({ pattern = null; enum_ = ?["PAYER", "PAYEE"]; minLength = null; maxLength = null })),
    ("TransactionInitiatorType", #string({ pattern = null; enum_ = ?["CONSUMER", "AGENT", "BUSINESS", "DEVICE"]; minLength = null; maxLength = null })),
    ("TransactionRequestState", #string({ pattern = null; enum_ = ?["RECEIVED", "PENDING", "ACCEPTED", "REJECTED"]; minLength = null; maxLength = null })),
    ("TransactionRequestsIDPutResponse", #object_({ properties = [("transactionId", #ref("CorrelationId")), ("transactionRequestState", #ref("TransactionRequestState")), ("extensionList", #ref("ExtensionList"))]; required = ["transactionRequestState"] })),
    ("TransactionRequestsPostRequest", #object_({ properties = [("transactionRequestId", #ref("CorrelationId")), ("payee", #ref("Party")), ("payer", #ref("PartyIdInfo")), ("amount", #ref("Money")), ("transactionType", #ref("TransactionType")), ("note", #ref("Note")), ("geoCode", #ref("GeoCode")), ("authenticationType", #ref("AuthenticationType")), ("expiration", #ref("DateTime")), ("extensionList", #ref("ExtensionList"))]; required = ["transactionRequestId", "payee", "payer", "amount", "transactionType"] })),
    ("TransactionScenario", #string({ pattern = null; enum_ = ?["DEPOSIT", "WITHDRAWAL", "TRANSFER", "PAYMENT", "REFUND"]; minLength = null; maxLength = null })),
    ("TransactionState", #string({ pattern = null; enum_ = ?["RECEIVED", "PENDING", "COMPLETED", "REJECTED"]; minLength = null; maxLength = null })),
    ("TransactionSubScenario", #string({ pattern = ?"^[A-Z_]{1,32}$"; enum_ = null; minLength = null; maxLength = null })),
    ("TransactionType", #object_({ properties = [("scenario", #ref("TransactionScenario")), ("subScenario", #ref("TransactionSubScenario")), ("initiator", #ref("TransactionInitiator")), ("initiatorType", #ref("TransactionInitiatorType")), ("refundInfo", #ref("Refund")), ("balanceOfPayments", #ref("BalanceOfPayments"))]; required = ["scenario", "initiator", "initiatorType"] })),
    ("TransactionsIDPutResponse", #object_({ properties = [("completedTimestamp", #ref("DateTime")), ("transactionState", #ref("TransactionState")), ("code", #ref("Code")), ("extensionList", #ref("ExtensionList"))]; required = ["transactionState"] })),
    ("TransferState", #string({ pattern = null; enum_ = ?["RECEIVED", "RESERVED", "COMMITTED", "ABORTED"]; minLength = null; maxLength = null })),
    ("TransfersIDPatchResponse", #object_({ properties = [("completedTimestamp", #ref("DateTime")), ("transferState", #ref("TransferState")), ("extensionList", #ref("ExtensionList"))]; required = ["completedTimestamp", "transferState"] })),
    ("TransfersIDPutResponse", #object_({ properties = [("fulfilment", #ref("IlpFulfilment")), ("completedTimestamp", #ref("DateTime")), ("transferState", #ref("TransferState")), ("extensionList", #ref("ExtensionList"))]; required = ["transferState"] })),
    ("TransfersPostRequest", #object_({ properties = [("transferId", #ref("CorrelationId")), ("payeeFsp", #ref("FspId")), ("payerFsp", #ref("FspId")), ("amount", #ref("Money")), ("ilpPacket", #ref("IlpPacket")), ("condition", #ref("IlpCondition")), ("expiration", #ref("DateTime")), ("extensionList", #ref("ExtensionList"))]; required = ["transferId", "payeeFsp", "payerFsp", "amount", "ilpPacket", "condition", "expiration"] })),
    ("U2FPIN", #string({ pattern = ?"^\\S{1,64}$"; enum_ = null; minLength = ?1; maxLength = ?64 })),
    ("U2FPinValue", #object_({ properties = [("pinValue", #allOf({ alternatives = [#ref("U2FPIN")]; pattern = null })), ("counter", #allOf({ alternatives = [#ref("Integer")]; pattern = null }))]; required = ["pinValue", "counter"] })),
  ];

  public func schema(name : Text) : ?Schema { for ((n, s) in SCHEMAS.vals()) { if (n == name) return ?s }; null };
}
