// EndOfDay.test.mo — the end-of-day batch end to end, through the real core.
//
// The the end-of-day batch criteria that are properties of the run rather than of the plan's
// arithmetic. `BatchPlan.test.mo` proves the plan on its own terms; this drives
// `prepareAdvanceEndOfDay` against a real embedded journal over a real portfolio:
//
//   E1  chunking does not change the result — the same date over the same portfolio
//       (≥ 500 accounts, 5 products, 2 currencies) run at `shardSize` 1, 7 and 1,000:
//       the journal state fingerprint is identical, the set of posting idempotency
//       keys is identical, every posted amount is identical, and the run totals agree
//   E2  interruption is survivable at every chunk boundary — the run stopped and
//       resumed at each boundary in turn ends with the journal fingerprint and the
//       posting-key set of the uninterrupted run
//   E3  a retried chunk posts nothing new — the crash window is the one between the
//       postings landing and the chunk block landing, so the chunk is re-derived with
//       the postings already in: every journal step comes back as `#existing`, naming
//       the very blocks the first attempt made, and nothing is posted
//   E4  a duplicate naming the wrong block is refused — a pre-existing posting under
//       the key a job would use, carrying different legs, makes the job fail with the
//       reason rather than record success, and the run advances past it
//   E5  inputs cannot move under a run — while a run for date D is open a posting
//       value-dated ≤ D is refused naming the run, one value-dated after D is
//       admitted, and after completion the back-valued posting is admitted
//   E6  a failing item does not stop the queue — twelve items rigged to fail
//       permanently, the run still completes, the cursor reaches the plan's end, each
//       failure is recorded with its reason, the declared retry limit is applied and
//       then the failure parks, and the period close is refused while any is unresolved
//   E7  the plan is fixed before the work — the opening block carries the plan's hash
//       and item count, and an account opened after the run opened is neither in the
//       plan nor processed
//   E8  jobs run in their declared order with their dependencies honoured, checked by
//       value: a percent-of-interest charge equals the rate times the interest job 1
//       accrued, the delinquency band reflects the instalments job 3 moved to due, and
//       the provision equals the band's declared percentage of the outstanding
//   E9  zero movement is examined, not posted — and no `#ZeroAmountLeg` is ever
//       generated by the batch
//   E10 an open advance path cannot choose content — the advance takes no content
//       argument at all, its postings are exactly the plan's, it cannot skip, and the
//       administrative acts around it are permissioned while it is not
//   E13 the statement cut is a record, not a re-derivation: it reproduces the same
//       figures after later back-valued activity is admitted
//   E15 the gate is a height — the batch posts nothing below the activation height,
//       and no administrative flag activates it
//
// E11 (value by value), E12 (independent ledgers), E13's camt.053
// projection and E14 (the independent verifier against the certified root) are the
// integration battery's: they need the oracles and the deployed canister, and they run
// in `integration/bank_s23.py`. E2's canister stop/start and upgrade at a boundary is
// there too — this battery covers interruption at every boundary in process, and the
// upgrade is a property of the installed canister.
//
// engine: wasi-only — the battery builds the portfolio several times over and
// fingerprints whole states, which does not finish in a useful time under `moc -r`.
// That is the same exemption the journal's core battery, and this repository's
// BankCore, PartyCore, ProductEngine and PeriodEnd batteries, already carry.

import Debug "mo:core/Debug";
import Nat "mo:core/Nat";
import Nat8 "mo:core/Nat8";
import Nat64 "mo:core/Nat64";
import Text "mo:core/Text";
import Blob "mo:core/Blob";
import Array "mo:core/Array";
import List "mo:core/List";
import Result "mo:core/Result";
import Principal "mo:core/Principal";

import JT "mo:journal/JournalTypes";
import JCore "mo:journal/JournalCore";
import CivilDate "mo:journal/CivilDate";

import T "../src/bank/BankTypes";
import ProdT "../src/bank/ProductTypes";
import Core "../src/bank/BankCore";
import ProductCore "../src/bank/ProductCore";
import BatchCore "../src/bank/BatchCore";
import Batch "../src/bank/Batch";
import BT "../src/bank/BatchTypes";
import Posting "../src/bank/Posting";
import Loans "../src/bank/Loans";
import Products "../src/bank/Products";
import I "../src/bank/Interest";
import P "../src/bank/Permissions";
import Conv "../src/bank/Conventions";
import Commit "../src/bank/Commitments";
import S "../src/bank/Screening";
import MT "../src/bank/MonitoringTypes";

import AlertCore "../src/bank/AlertCore";
import BankMemLog "support/BankMemLog";
import JMemLog "support/JournalMemLog";

// ─── the calendar and the dates ──────────────────────────────────────────────

func day(y : Nat, m : Nat, d : Nat) : JT.Day {
  switch (CivilDate.fromCivil(y, m, d)) { case (?x) x; case null { Debug.print("bad date"); assert false; 0 } }
};
func dtext(d : JT.Day) : Text { CivilDate.toText(d) };

let JAN1 = day(2026, 1, 1);
let OPEN = day(2026, 1, 5);      // the day every account is funded and every loan drawn
let EOD = day(2026, 4, 5);       // the business date the batch runs for

/// What the batch's monitoring job asks of each account on the date. The engine's own evaluation
/// over the aggregates is the monitoring oracle's business (`Monitoring.test.mo`); here the hook is
/// what the alert battery below sets, so the job's mechanics — opening once, failing on a refusal,
/// examining every account — are tested with an evaluation this file controls.
var monitorHook : (Nat, Nat) -> Result.Result<[MT.Finding], MT.MonitoringError> = Core.noMonitor;
let MAY1 = day(2026, 5, 1);      // the wall clock, past the period, so April can be closed
let DAY_NS : Nat64 = 86_400_000_000_000;
let clock : Nat64 = Nat64.fromNat(MAY1) * DAY_NS + 43_200_000_000_000;

let months : [(Text, JT.Day, JT.Day)] = [
  ("2026-01", JAN1, day(2026, 1, 31)),
  ("2026-02", day(2026, 2, 1), day(2026, 2, 28)),
  ("2026-03", day(2026, 3, 1), day(2026, 3, 31)),
  ("2026-04", day(2026, 4, 1), day(2026, 4, 30)),
];
let calConfig : JT.CalendarConfig = {
  restDays = [4, 5];                                  // Friday and Saturday
  holidays = Array.sort<JT.Day>([day(2026, 1, 7), day(2026, 1, 25)], Nat.compare);
  policy = #reject;
};

let bankP = Principal.fromBlob("\BA\01");
let installer = Principal.fromBlob("\1A\01");
let screener = Principal.fromBlob("\5C\01");
let cashier = Principal.fromBlob("\C0\01");

func rate(n : Nat, d : Nat) : I.Rate { { numerator = n; denominator = d; negative = false } };
func flatChart(r : I.Rate) : ProdT.RateChart { { bands = [{ from = 0; to = null; rate = r }]; by = #balance } };

// ─── the portfolio a world is built to ───────────────────────────────────────

type Spec = {
  curs : Nat;          // current accounts, EGP, with two charges due on the run date
  savs : Nat;          // savings, EGP
  loans : Nat;         // loans, EGP, in arrears with an instalment due on the run date
  fds : Nat;           // term deposits, EGP
  usds : Nat;          // savings, USD
  dry : Nat;           // current accounts left unfunded, so their charges round to zero
  instructions : Nat;  // standing instructions that can be paid
  failing : Nat;       // standing instructions that cannot be paid
  openTill : Bool;     // leave a till unsettled, so the till check fails
  /// The accounting periods to open. The default is the four months below; a battery that
  /// has to drive a period close declares a shorter one, because the accrual cut-off is
  /// satisfied only when every business day of the period has been accrued and a run is
  /// for one day.
  periods : [(Text, JT.Day, JT.Day)];
  /// Whether to activate the money-visible features. A world built with them off is how
  /// E15 shows that the gate is a height and not a habit.
  activate : Bool;
};

type World = {
  bs : Core.State;
  js : JCore.State;
  cmd : T.Command -> Nat;
  post : T.Command -> [Nat];
  refuse : (T.Command, Text) -> ();
  refuseUnmoved : (T.Command, Text) -> ();
  jraw : JT.Event -> JT.Block;
  /// Advance the open run by up to `limit` items. The run records as it goes, through
  /// the same append-and-apply the actor uses, so there is nothing left to commit
  /// afterwards.
  advance : Nat -> Core.Advance;
  /// The journal's record reader for this world's own chain. A posting's record lives in the block log,
  /// so every read that needs one goes through this.
  jb : JCore.Blocks;
  /// The bank's own reader, for the records that live in its blocks: the parties, accounts and tills.
  bb : Core.Blocks;
  bchain : BankMemLog.Chain;
  tryAdvance : Nat -> Result.Result<Core.Advance, T.BankError>;
  /// The same, but the bank's own blocks are thrown away while the journal's are kept:
  /// the state a canister would be in if it stopped between the postings landing and the
  /// chunk block landing. E3 re-derives the chunk from there.
  advanceLosingBankBlocks : Nat -> Core.Advance;
  party : Nat;
  curs : [Nat];
  savs : [Nat];
  loans : [Nat];
  fds : [Nat];
  usds : [Nat];
  dry : [Nat];
};

func build(spec : Spec) : World {
  let bchain = BankMemLog.new();
  let jchain = JMemLog.new();
  let bs = Core.newState(installer);
  let js = JCore.newState(bankP);

  func bcommit(caller : Principal, e : T.Event) : T.Block { BankMemLog.commit(bchain, bs, clock, caller, e) };
  func jcommit(e : JT.Event) : JT.Block { JMemLog.commit(jchain, js, clock, bankP, e) };

  var authority = 1_000_000;
  func nextAuthority() : Nat { authority += 1; authority };

  func execute(command : T.Command, authorityIndex : Nat) : [Nat] {
    switch (Core.planCommand(bs, BankMemLog.reader(bchain), js, JMemLog.reader(jchain), bankP, clock, command, authorityIndex)) {
      case (#err(e)) { Debug.print("plan failed for " # P.commandName(command) # ": " # debug_show (e)); assert false; [] };
      case (#ok(plan)) {
        switch (plan.bankEvent) { case (?ev) { ignore bcommit(installer, ev) }; case null {} };
      for (ev in plan.extra.vals()) { ignore bcommit(installer, ev) };
        let out = List.empty<Nat>();
        for (step in plan.journal.vals()) {
          switch (step) { case (#event(ev)) List.add(out, jcommit(ev).index); case (#existing(i)) List.add(out, i) };
        };
        List.toArray(out)
      };
    }
  };
  func cmd(command : T.Command) : Nat { let at = Core.height(bs); ignore execute(command, nextAuthority()); at };
  func post(command : T.Command) : [Nat] { execute(command, nextAuthority()) };

  /// A refusal that leaves nothing behind. The cheap form compares heights, which is
  /// what a 500-account world can afford on every call; `refuseUnmoved` compares the
  /// whole of both states and is used where a criterion asks for it.
  func refuse(command : T.Command, want : Text) {
    let bh = Core.height(bs);
    let jh = JCore.height(js);
    switch (Core.planCommand(bs, BankMemLog.reader(bchain), js, JMemLog.reader(jchain), bankP, clock, command, nextAuthority())) {
      case (#ok(_)) { Debug.print("expected " # want # " for " # P.commandName(command)); assert false };
      case (#err(e)) {
        let got = debug_show (e);
        if (not Text.contains(got, #text want)) { Debug.print("wanted " # want # " got " # got); assert false };
      };
    };
    assert (Core.height(bs) == bh and JCore.height(js) == jh);
  };
  func refuseUnmoved(command : T.Command, want : Text) {
    let bf = Core.fingerprint(bs);
    let jf = JCore.fingerprint(js);
    refuse(command, want);
    assert (Core.fingerprint(bs) == bf);
    assert (JCore.fingerprint(js) == jf);
  };

  /// The postings of a run are attributed to the canister, which is what makes an open
  /// advance path safe: `bankP` here is the canister's own principal.
  let recorder : Core.Recorder = {
    bank = func(ev : T.Event) : Nat { bcommit(bankP, ev).index };
    journal = func(ev : JT.Event) : Nat { jcommit(ev).index };
    monitor = func(a : Nat, d : Nat) : Result.Result<[MT.Finding], MT.MonitoringError> { monitorHook(a, d) };
  };
  /// The same, with the bank's own blocks discarded: the journal moves and the bank's
  /// record of it does not.
  let lossyRecorder : Core.Recorder = {
    bank = func(_ : T.Event) : Nat { 0 };
    journal = func(ev : JT.Event) : Nat { jcommit(ev).index };
    monitor = func(a : Nat, d : Nat) : Result.Result<[MT.Finding], MT.MonitoringError> { monitorHook(a, d) };
  };
  func tryAdvance(limit : Nat) : Result.Result<Core.Advance, T.BankError> {
    Core.runEndOfDayChunk(bs, BankMemLog.reader(bchain), js, JMemLog.reader(jchain), bankP, clock, "BR01", EOD, limit, recorder)
  };
  func advance(limit : Nat) : Core.Advance {
    switch (tryAdvance(limit)) {
      case (#err(e)) { Debug.print("advance failed: " # debug_show (e)); assert false; loop {} };
      case (#ok(a)) a;
    }
  };
  func advanceLosingBankBlocks(limit : Nat) : Core.Advance {
    switch (Core.runEndOfDayChunk(bs, BankMemLog.reader(bchain), js, JMemLog.reader(jchain), bankP, clock, "BR01", EOD, limit, lossyRecorder)) {
      case (#err(e)) { Debug.print("advance failed: " # debug_show (e)); assert false; loop {} };
      case (#ok(a)) a;
    }
  };

  // ── genesis ────────────────────────────────────────────────────────────────
  ignore jcommit(switch (JCore.prepareAddPoster(js, bankP, bankP)) { case (#ok(e)) e; case (#err(_)) { assert false; loop {} } });
  ignore bcommit(installer, #bankAdminTransferred({ admin = installer }));
  ignore cmd(#openBook({ id = "HQ"; name = "Head office"; parent = null }));
  ignore cmd(#openBook({ id = "BR01"; name = "Branch 1"; parent = ?"HQ" }));
  ignore cmd(#journalRegisterCurrency({ code = "EGP"; minorUnits = 2 }));
  ignore cmd(#journalRegisterCurrency({ code = "USD"; minorUnits = 2 }));

  let chart : [(Text, Text, JT.Side, JT.Category)] = [
    ("1001", "Cash and vault", #debit, #asset),
    ("1205", "Overdrafts", #debit, #asset),
    ("1210", "Loan portfolio", #debit, #asset),
    ("1220", "Interest receivable", #debit, #asset),
    ("1230", "Fees receivable", #debit, #asset),
    ("1240", "Penalties receivable", #debit, #asset),
    ("1290", "Allowance for credit losses", #debit, #asset),
    ("1900", "Suspense", #debit, #asset),
    ("1999", "Settlement", #debit, #asset),
    ("2110", "Customer deposits", #credit, #liability),
    ("2115", "Term deposits", #credit, #liability),
    ("2120", "Interest payable", #credit, #liability),
    ("4100", "Fee income", #credit, #income),
    ("4110", "Penalty income", #credit, #income),
    ("4200", "Interest income", #credit, #income),
    ("4300", "Recoveries", #credit, #income),
    ("5100", "Interest expense", #debit, #expense),
    ("5200", "Impairment expense", #debit, #expense),
    ("5210", "Loans written off", #debit, #expense),
  ];
  for ((code, name, side, cat) in chart.vals()) {
    ignore cmd(#journalOpenAccount({ code; name; normalSide = side; category = cat; constraint = #none }));
  };
  for ((id, start, end) in spec.periods.vals()) { ignore cmd(#journalOpenPeriod({ id; start; end })) };
  ignore cmd(#journalSetCalendar({ calendar = ?calConfig }));
  ignore cmd(#journalRollBusinessDate({ day = OPEN }));
  ignore cmd(#journalSetActivationHeight({ height = 0 }));
  ignore cmd(#setAccountFormat({ country = "EG"; bank = "0037"; branch = "0001"; serialWidth = 12; prefix = "00000" }));
  ignore cmd(#addStaff({ principal_ = cashier; book = "BR01"; title = "Cashier" }));
  // the whole quarter is value-dated into, so the branch's window is declared wide
  for (b in ["HQ", "BR01"].vals()) {
    ignore cmd(#setBackValueWindow({ window = { book = b; freeDays = 200; approvedDays = 0 } }));
  };
  // The functional currency the close reports in (decision D-7). Declaring it is
  // configuration and moves nothing; it is here because a revaluation step refuses
  // without it, and a batch battery that could not reach a close could not show that an
  // unresolved failure blocks one.
  ignore cmd(#setFunctionalCurrency({ currency = "EGP" }));

  // ── one party every account belongs to ─────────────────────────────────────
  func saltFor(i : Nat) : Blob { Blob.fromArray(Array.tabulate<Nat8>(32, func(j) { Nat8.fromNat((i * 31 + j) % 256) })) };
  let institutionSalt = saltFor(99);
  let entries = Array.sort<Blob>(Array.map<Text, Blob>(["AL QAIDA"], func(t) { S.entryBytes(t) }), func(a, b) { S.compareEntries(a, b) });
  let ?listRoot = S.root(entries) else { assert false; loop {} };
  ignore cmd(#commitScreeningList({ version = "L1"; root = listRoot; count = 1; normalisation = Commit.NORMALISATION }));
  let salt = saltFor(1);
  let party = cmd(#createParty({
    kind = #natural; salt;
    identityCommit = Commit.identity(salt, #natural, ["Person 1", "29801011234561"]);
    dedupCommit = ?Commit.dedup(institutionSalt, "nationalId", "29801011234561");
    attributes = []; book = "BR01"; cddLevel = #standard; riskRating = #low; pep = false;
    reviewDue = EOD + 365;
  }));
  ignore cmd(#setPartyLifecycle({ party; to = #pendingKyc }));
  for (kind in ["identity", "address"].vals()) {
    ignore cmd(#addPartyDocument({ party; document = { kind; commit = Commit.document(salt, kind, Blob.fromArray([1])); issued = 20000; expires = null } }));
  };
  ignore cmd(#recordScreeningDecision({ party; listVersion = "L1"; listRoot; decision = #clear; screener; justificationCommit = Commit.justification("no match") }));
  ignore cmd(#setPartyLifecycle({ party; to = #active }));

  // ── the products ───────────────────────────────────────────────────────────
  let depositInterest : ProdT.InterestTerms = {
    chart = flatChart(rate(5, 100));
    convention = #a004_Act365Fixed;
    basis = #dailyBalance;
    compounding = #monthly;
    compoundingAlignment = #anniversary;
    posting = #monthly;
    minimumBalance = 0;
    allowNegative = false;
  };
  let savings : ProdT.ProductTerms = {
    kind = #savings;
    currency = "EGP";
    control = "2110";
    roles = [
      { role = #principal; account = "2110" },
      { role = #interestPayable; account = "2120" },
      { role = #interestExpense; account = "5100" },
      { role = #feeIncome; account = "4100" },
    ];
    interest = ?depositInterest;
    charges = [];
    limits = { overdraft = null; minimumOperating = 0; perOperation = null };
    schedule = null;
    delinquency = [];
    provisioning = [];
    accounting = #accrualPeriodic;
    withholdingTax = null;
    rounding = #halfEven;
    earlyRedemptionPenalty = null;
    valueDateConvention = #sameDay;
  };
  ignore cmd(#registerProduct({ id = "SAV"; name = "Savings"; terms = savings }));
  ignore cmd(#registerProduct({ id = "SAVUSD"; name = "Savings, dollars"; terms = { savings with currency = "USD" } }));

  // A current account carrying both charges E8 compares by value: a flat one and a
  // percentage of the interest job 1 accrued for the same day.
  ignore cmd(#registerProduct({
    id = "CUR"; name = "Current account";
    terms = { savings with
      kind = #currentAccount;
      roles = [
        { role = #principal; account = "2110" },
        { role = #interestPayable; account = "2120" },
        { role = #interestExpense; account = "5100" },
        { role = #feeIncome; account = "4100" },
        { role = #overdraftPortfolio; account = "1205" },
      ];
      charges = [
        { id = "ledger-fee"; calculation = #flat({ amount = 1_000 }); timing = #onDate({ day = EOD }); currency = "EGP"; role = #feeIncome; waivable = true },
        { id = "interest-fee"; calculation = #percentOfInterest({ rate = rate(10, 100) }); timing = #onDate({ day = EOD }); currency = "EGP"; role = #feeIncome; waivable = true },
      ];
    };
  }));

  // The product E9 is about: its only charge is a percentage of interest, so on an
  // account with no balance there is no interest and the charge rounds to zero —
  // examined, counted as zero movement, and never posted as a zero-amount leg.
  ignore cmd(#registerProduct({
    id = "CURZ"; name = "Current account, fee on interest only";
    terms = { savings with
      kind = #currentAccount;
      roles = [
        { role = #principal; account = "2110" },
        { role = #interestPayable; account = "2120" },
        { role = #interestExpense; account = "5100" },
        { role = #feeIncome; account = "4100" },
        { role = #overdraftPortfolio; account = "1205" },
      ];
      charges = [
        { id = "interest-fee"; calculation = #percentOfInterest({ rate = rate(10, 100) }); timing = #onDate({ day = EOD }); currency = "EGP"; role = #feeIncome; waivable = true },
      ];
    };
  }));

  ignore cmd(#registerProduct({
    id = "FD"; name = "Term deposit";
    terms = { savings with kind = #termDeposit; control = "2115";
      // a term-banded chart, so the account's rate is fixed at opening and the
      // maturity job has the rate it is entitled to pay
      interest = ?{ depositInterest with chart = { bands = [{ from = 0; to = null; rate = rate(7, 100) }]; by = #termDays } };
      roles = [
        { role = #principal; account = "2115" },
        { role = #interestPayable; account = "2120" },
        { role = #interestExpense; account = "5100" },
        { role = #penaltyIncome; account = "4110" },
      ];
    };
  }));

  ignore cmd(#registerProduct({
    id = "LOAN"; name = "Term loan";
    terms = {
      kind = #loan;
      currency = "EGP";
      control = "1210";
      roles = [
        { role = #principal; account = "1210" },
        { role = #interestReceivable; account = "1220" },
        { role = #interestIncome; account = "4200" },
        { role = #feeIncome; account = "4100" },
        { role = #penaltyIncome; account = "4110" },
        { role = #feeReceivable; account = "1230" },
        { role = #penaltyReceivable; account = "1240" },
        { role = #writeOff; account = "5210" },
        { role = #recovery; account = "4300" },
        { role = #allowance; account = "1290" },
        { role = #impairmentExpense; account = "5200" },
      ];
      interest = ?{ depositInterest with chart = flatChart(rate(12, 100)) };
      charges = [];
      limits = { overdraft = null; minimumOperating = 0; perOperation = null };
      schedule = ?{ amortisation = #equalInstalments; instalments = 6; every = #monthly; principalGrace = 0; interestGrace = 0; moratoriumDays = 0 };
      delinquency = [
        { name = "current"; fromDays = 0; toDays = ?31 },
        { name = "31-60"; fromDays = 31; toDays = ?61 },
        { name = "61+"; fromDays = 61; toDays = null },
      ];
      provisioning = [
        { band = "current"; stage = 1; percentOfOutstanding = rate(1, 100) },
        { band = "31-60"; stage = 2; percentOfOutstanding = rate(20, 100) },
        { band = "61+"; stage = 3; percentOfOutstanding = rate(100, 100) },
      ];
      accounting = #accrualPeriodic;
      withholdingTax = null;
      rounding = #halfEven;
      earlyRedemptionPenalty = null;
      valueDateConvention = #sameDay;
    };
  }));

  ignore cmd(#registerProduct({
    id = "TILL"; name = "Cashier drawer";
    terms = { savings with kind = #till; control = "1001"; accounting = #cash;
      interest = null; charges = [];
      roles = [
        { role = #principal; account = "1001" },
        { role = #cash; account = "1001" },
        { role = #suspense; account = "1900" },
      ];
    };
  }));

  if (spec.activate) {
    for (f in ProdT.featureIds().vals()) {
      ignore cmd(#setFeatureActivation({ feature = f; height = Nat64.fromNat(Core.height(bs)) }));
    };
  };

  // ── the accounts ───────────────────────────────────────────────────────────
  func openMany(product : Text, ccy : Text, n : Nat, fund : Nat) : [Nat] {
    let out = List.empty<Nat>();
    var i = 0;
    while (i < n) {
      let a = cmd(#openAccount({ product; party; currency = ccy; termDays = null; allocationOrder = [] }));
      ignore cmd(#setAccountStatus({ account = a; to = #active }));
      if (fund > 0) {
        ignore post(#depositToAccount({
          account = a; amount = fund; postingDate = OPEN; valueDate = OPEN;
          period = "2026-01"; narration = "opening deposit"; funding = #glAccount("1999");
        }));
      };
      List.add(out, a);
      i += 1;
    };
    List.toArray(out)
  };

  let curs = openMany("CUR", "EGP", spec.curs, 10_000_00);
  let savs = openMany("SAV", "EGP", spec.savs, 25_000_00);
  let dry = openMany("CURZ", "EGP", spec.dry, 0);
  let usds = openMany("SAVUSD", "USD", spec.usds, 5_000_00);

  let fdList = List.empty<Nat>();
  var k = 0;
  while (k < spec.fds) {
    let a = cmd(#openAccount({ product = "FD"; party; currency = "EGP"; termDays = ?90; allocationOrder = [] }));
    ignore cmd(#setAccountStatus({ account = a; to = #active }));
    ignore post(#depositToAccount({
      account = a; amount = 50_000_00; postingDate = OPEN; valueDate = OPEN;
      period = "2026-01"; narration = "term deposit"; funding = #glAccount("1999");
    }));
    List.add(fdList, a);
    k += 1;
  };
  let fds = List.toArray(fdList);

  let loanList = List.empty<Nat>();
  var m = 0;
  while (m < spec.loans) {
    let a = cmd(#openAccount({ product = "LOAN"; party; currency = "EGP"; termDays = null; allocationOrder = [] }));
    ignore cmd(#setAccountStatus({ account = a; to = #active }));
    ignore post(#disburseLoan({
      account = a; amount = 60_000_00; postingDate = OPEN; valueDate = OPEN;
      period = "2026-01"; narration = "drawdown"; funding = #glAccount("1999");
    }));
    List.add(loanList, a);
    m += 1;
  };
  let loans = List.toArray(loanList);

  // ── standing instructions, some payable and some not ───────────────────────
  // A payable one moves money between two funded savings accounts; a failing one pays
  // out of an account that has none, which the journal's own sub-ledger limit refuses.
  var s = 0;
  while (s < spec.instructions and s + 1 < savs.size()) {
    ignore cmd(#defineStandingInstruction({ instruction = {
      id = "si-ok-" # Nat.toText(s); book = "BR01";
      from = savs[s]; to = savs[s + 1]; amount = 100_00; currency = "EGP";
      everyDays = 1; startDay = OPEN; endDay = null; narration = "standing transfer";
    } }));
    s += 1;
  };
  var f = 0;
  while (f < spec.failing and f < dry.size()) {
    ignore cmd(#defineStandingInstruction({ instruction = {
      id = "si-bad-" # Nat.toText(f); book = "BR01";
      from = dry[f]; to = savs[0]; amount = 500_00; currency = "EGP";
      everyDays = 1; startDay = OPEN; endDay = null; narration = "unpayable transfer";
    } }));
    f += 1;
  };

  // ── a till, left open so the close-of-day check has something to refuse ────
  if (spec.openTill) {
    ignore cmd(#openTill({ till = "T1"; book = "BR01"; currency = "EGP"; holder = cashier; product = "TILL" }));
    ignore post(#allocateCashToTill({ till = "T1"; amount = 5_000_00; postingDate = OPEN; valueDate = OPEN; period = "2026-01"; narration = "float" }));
  };

  // ── the business date moves to the run date ────────────────────────────────
  ignore cmd(#journalRollBusinessDate({ day = EOD }));

  { bs; js; jb = JMemLog.reader(jchain); bb = BankMemLog.reader(bchain); bchain; cmd; post; refuse; refuseUnmoved; jraw = jcommit; advance; tryAdvance; advanceLosingBankBlocks; party; curs; savs; loans; fds; usds; dry }
};

// ─── reading a world back ────────────────────────────────────────────────────

/// Every posting idempotency key in the journal, in block order. E1 and E2 compare
/// these sets: two runs that posted the same money named the same keys.
func postingKeys(js : JCore.State, jb : JCore.Blocks) : [Blob] {
  let out = List.empty<Blob>();
  var i = 0;
  let h = JCore.height(js);
  while (i < h) {
    switch (JCore.postingView(js, jb, i)) { case (?v) List.add(out, v.record.idempotencyKey); case null {} };
    i += 1;
  };
  List.toArray(out)
};

func keyText(b : Blob) : Text {
  var t = "";
  for (x in b.vals()) { t #= Nat.toText(Nat8.toNat(x)) # "." };
  t
};

/// Every posting's legs, flattened to a comparable string, so "every posted amount is
/// identical" is checked by value and not only by count.
func postingDigest(js : JCore.State, jb : JCore.Blocks) : Text {
  var t = "";
  var i = 0;
  let h = JCore.height(js);
  while (i < h) {
    switch (JCore.postingView(js, jb, i)) {
      case (?v) {
        t #= keyText(v.record.idempotencyKey) # "|" # Nat.toText(v.record.valueDate) # "|";
        for (l in v.record.legs.vals()) {
          t #= l.account # "/" # (switch (l.subledger) { case (?sl) keyText(sl); case null "-" }) # "/"
            # (switch (l.side) { case (#debit) "D"; case (#credit) "C" }) # "/" # l.currency # "/" # Nat.toText(l.amount) # ";";
        };
        t #= "\n";
      };
      case null {};
    };
    i += 1;
  };
  t
};

/// The first `n` of an array, which is all a by-value check over identical accounts
/// needs: every account of a product in this portfolio was opened and funded the same
/// way, so five of them exercise the arithmetic and five hundred would only cost time.
func firstFew(xs : [Nat], n : Nat) : [Nat] {
  Array.tabulate<Nat>(if (n < xs.size()) n else xs.size(), func(i) { xs[i] })
};

func runOf(w : World) : BatchCore.RunEntry {
  switch (BatchCore.getRun(w.bs.batch, "BR01", EOD)) { case (?r) r; case null { Debug.print("no run"); assert false; loop {} } }
};

/// Open a run and work it to completion in chunks of `limit`, returning how many
/// advances it took. The guard is a bound, not an expectation: a run that does not
/// finish inside it is a run whose cursor is not advancing, which is a failure.
func workOpen(w : World, limit : Nat) : Nat {
  var advances = 0;
  while (not BatchCore.isComplete(runOf(w))) {
    ignore w.advance(limit);
    advances += 1;
    if (advances > 4_000) { Debug.print("the run did not finish"); assert false };
  };
  advances
};

func workWhole(w : World, shardSize : Nat, limit : Nat) : Nat {
  ignore w.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize }));
  workOpen(w, limit)
};

/// No batch failure anywhere in this battery may be a zero-amount leg: a job that would
/// post nothing must count it as zero movement and not submit it. Every failure text the
/// battery sees passes through here.
var zeroLegFailures = 0;
var failuresSeen = 0;
func inspectFailures(r : BatchCore.RunEntry) {
  for (f in BatchCore.failuresOf(r).vals()) {
    failuresSeen += 1;
    assert (Text.size(f.error) > 0);
    assert (Text.size(f.entity) > 0);
    if (Text.contains(f.error, #text "ZeroAmountLeg")) zeroLegFailures += 1;
  };
};

// ═══════════════════════════════════════════════════════════════════════════
//  E7 — the plan is fixed before the work
// ═══════════════════════════════════════════════════════════════════════════

let e7 = build({ curs = 4; savs = 5; loans = 3; fds = 2; usds = 2; dry = 2; instructions = 2; failing = 0; openTill = false; periods = months; activate = true });
ignore e7.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }));
let r7 = runOf(e7);

// the opening block's hash and counts are the plan's own, re-derived from the inputs
// the block recorded rather than from whatever the state happens to be now
func derivedPlan(w : World, r : BatchCore.RunEntry) : [Batch.PlanItem] {
  switch (Batch.plan(Core.planInput(w.bs, r.book, r.businessDate, r.openedAtBlock, r.shardSize))) {
    case (#ok(items)) items;
    case (#err(e)) { Debug.print(debug_show (e)); assert false; [] };
  }
};
let plan7 = derivedPlan(e7, r7);
assert (Batch.planHash(plan7) == r7.planHash);
assert (plan7.size() == r7.items);
// the entities are the opening's figure, from the folds' counters: every account of the products the plan walks in
// the book, plus one per accruing product, plus the book's instructions and tills (never a hash input)
assert (r7.entities == Core.planEntities(e7.bs, e7.bb, r7.book, plan7));
assert (r7.entities > 0);
assert (r7.planHash.size() == 32);
Debug.print("count: plan items the opening block fixed = " # Nat.toText(r7.items));
Debug.print("count: entities the opening block fixed = " # Nat.toText(r7.entities));

// a second run for the same date is refused: the plan is fixed once
e7.refuse(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }), "RunExists");
// and a run for a date the journal is not on is refused, so a run cannot be opened for
// a book that is either not closed yet or already reopened
e7.refuse(#openEndOfDay({ book = "BR01"; businessDate = EOD + 1; shardSize = 4 }), "BusinessDateMismatch");
e7.refuse(#openEndOfDay({ book = "BR01"; businessDate = OPEN; shardSize = 4 }), "BusinessDateMismatch");
Debug.print("count: run openings refused = 3");

// an account opened after the run opened is above the recorded ceiling, is not in the
// plan, and is not processed
let late = e7.cmd(#openAccount({ product = "SAV"; party = e7.party; currency = "EGP"; termDays = null; allocationOrder = [] }));
assert (late > r7.maxAccount);
let planAfter = derivedPlan(e7, r7);
assert (Batch.planHash(planAfter) == r7.planHash);
assert (planAfter.size() == plan7.size());
ignore workOpen(e7, 8);         // the run was already open; this works it to the end
let after7 = runOf(e7);
assert (after7.cursor == after7.items);
assert (BatchCore.cutFor(e7.bs.batch, late) == null);
for (a in e7.savs.vals()) { assert (BatchCore.cutFor(e7.bs.batch, a) != null) };
inspectFailures(after7);
Debug.print("accounts opened after the run that the run processed: none, and the one opened was checked");

// ═══════════════════════════════════════════════════════════════════════════
//  E1 — chunking does not change the result
// ═══════════════════════════════════════════════════════════════════════════

// Six products, two currencies, 502 accounts. Nothing in this portfolio fails, so the
// comparison is of the whole result and not of a result plus a pile of exceptions.
let bigSpec : Spec = { curs = 120; savs = 180; loans = 90; fds = 40; usds = 60; dry = 12; instructions = 5; failing = 0; openTill = false; periods = months; activate = true };
let accountTotal = bigSpec.curs + bigSpec.savs + bigSpec.loans + bigSpec.fds + bigSpec.usds + bigSpec.dry;
Debug.print("count: accounts in the compared portfolio = " # Nat.toText(accountTotal));
assert (accountTotal >= 500);

let sizes = [1, 7, 1_000];
let worlds = Array.map<Nat, World>(sizes, func(_) { build(bigSpec) });

// the worlds are built identically, so they start identical — asserted, because the
// comparison that follows means nothing otherwise
assert (JCore.fingerprint(worlds[0].js) == JCore.fingerprint(worlds[1].js));
assert (JCore.fingerprint(worlds[1].js) == JCore.fingerprint(worlds[2].js));
assert (Core.fingerprint(worlds[0].bs) == Core.fingerprint(worlds[1].bs));
Debug.print("count: identically built worlds = 3");

let chunkCounts = Array.tabulate<Nat>(sizes.size(), func(i) { workWhole(worlds[i], sizes[i], Batch.MAX_ADVANCE_LIMIT) });
Debug.print("advances taken at shard sizes " # debug_show (sizes) # " = " # debug_show (chunkCounts));
// the chunking really did differ, so the equality below is not vacuous
assert (chunkCounts[0] > chunkCounts[2]);

let runs = Array.tabulate<BatchCore.RunEntry>(sizes.size(), func(i) { runOf(worlds[i]) });
for (i in runs.keys()) {
  inspectFailures(runs[i]);
  assert (BatchCore.failureCount(runs[i]) == 0);
  assert (runs[i].cursor == runs[i].items);
  Debug.print("shard " # Nat.toText(sizes[i]) # ": items " # Nat.toText(runs[i].items)
    # " entities " # Nat.toText(runs[i].entities) # " posted " # Nat.toText(runs[i].posted)
    # " examined " # Nat.toText(runs[i].examined) # " zero " # Nat.toText(runs[i].zeroMovement)
    # " chunks " # Nat.toText(runs[i].chunks));
};
// the item count no longer changes with the shard size — an item is a walk, the size is its page — so the plan's
// hash is the same at every size and the number of chunks is what moves (S4.1 audit, finding A1)
assert (runs[0].items == runs[2].items and runs[0].planHash == runs[2].planHash);
assert (runs[0].chunks > runs[2].chunks);
var i1 = 1;
while (i1 < runs.size()) {
  assert (runs[i1].posted == runs[0].posted);
  assert (runs[i1].examined == runs[0].examined);
  assert (runs[i1].zeroMovement == runs[0].zeroMovement);
  assert (runs[i1].entities == runs[0].entities);
  assert (runs[i1].maxAccount == runs[0].maxAccount);
  i1 += 1;
};
// examined is at least the entity count and is not the same measure: the aggregate
// accrual names one entity per product and examines every account of it
assert (runs[0].examined >= runs[0].entities);
Debug.print("count: run totals equal across shard sizes = 5");

// the money itself: the same keys, the same legs, the same journal state
let keySets = Array.map<World, [Blob]>(worlds, func(w) { postingKeys(w.js, w.jb) });
let digests = Array.map<World, Text>(worlds, func(w) { postingDigest(w.js, w.jb) });
Debug.print("count: postings in the journal after the run = " # Nat.toText(keySets[0].size()));
var i2 = 1;
while (i2 < worlds.size()) {
  if (keySets[i2].size() != keySets[0].size()) {
    Debug.print("shard " # Nat.toText(sizes[i2]) # " made " # Nat.toText(keySets[i2].size()) # " postings, shard 1 made " # Nat.toText(keySets[0].size()));
    assert false;
  };
  var k = 0;
  while (k < keySets[0].size()) {
    if (keySets[i2][k] != keySets[0][k]) { Debug.print("posting key " # Nat.toText(k) # " differs at shard " # Nat.toText(sizes[i2])); assert false };
    k += 1;
  };
  if (not Text.equal(digests[i2], digests[0])) { Debug.print("the posted legs differ at shard " # Nat.toText(sizes[i2])); assert false };
  if (JCore.fingerprint(worlds[i2].js) != JCore.fingerprint(worlds[0].js)) {
    Debug.print("the journal state differs at shard " # Nat.toText(sizes[i2]));
    assert false;
  };
  i2 += 1;
};
Debug.print("count: shard sizes whose journal state is identical = " # Nat.toText(sizes.size()));
// and the keys really are distinct, so "identical sets" is not "one key three times"
let sorted = Array.sort<Blob>(keySets[0], Blob.compare);
var duplicates = 0;
var k2 = 1;
while (k2 < sorted.size()) {
  if (sorted[k2] == sorted[k2 - 1]) duplicates += 1;
  k2 += 1;
};
Debug.print("duplicate posting keys in the journal: " # Nat.toText(duplicates) # " of " # Nat.toText(sorted.size()) # " keys");
assert (duplicates == 0);
Debug.print("count: distinct posting keys compared for duplicates = " # Nat.toText(sorted.size()));

// ═══════════════════════════════════════════════════════════════════════════
//  E9 (in the compared run) — zero movement is examined, not posted
// ═══════════════════════════════════════════════════════════════════════════

let w1000 = worlds[2];
let r1000 = runs[2];
assert (r1000.zeroMovement > 0);
// The dry accounts' only charge is a percentage of interest they did not earn. Every one
// of them was examined, counted as zero movement, and never posted.
var dryChecked = 0;
for (a in w1000.dry.vals()) {
  let key = Posting.key("charge", [Nat.toText(a), "interest-fee", Nat.toText(EOD)]);
  assert (JCore.postingIndexByKey(w1000.js, bankP, key) == null);
  dryChecked += 1;
};
Debug.print("count: accounts whose charge rounded to zero and posted nothing = " # Nat.toText(dryChecked));
assert (dryChecked == bigSpec.dry);
// and every one of them still has a statement cut, so "nothing happened" is recorded
for (a in w1000.dry.vals()) { assert (BatchCore.cutFor(w1000.bs.batch, a) != null) };
Debug.print("count: zero-movement accounts with a statement cut = " # Nat.toText(dryChecked));

// ═══════════════════════════════════════════════════════════════════════════
//  E8 — jobs in their declared order, with their dependencies, by value
// ═══════════════════════════════════════════════════════════════════════════

// 1. a percent-of-interest charge equals the rate times the interest job 1 accrued for
//    the same account and the same day. The interest is read back independently through
//    the public window accrual, and the rate is applied here rather than by the charge
//    module, so the two arithmetics are separate.
var chargeChecks = 0;
for (a in firstFew(w1000.curs, 5).vals()) {
  let accrued = switch (Core.accruedBetween(w1000.bs, w1000.bb, w1000.js, a, EOD, EOD + 1)) {
    case (#ok(v)) v;
    case (#err(e)) { Debug.print(debug_show (e)); assert false; loop {} };
  };
  assert (accrued.amount > 0);
  let expected = I.round({ numerator = accrued.amount * 10; denominator = 100; negative = false }, #halfEven).amount;
  let ?idx = JCore.postingIndexByKey(w1000.js, bankP, Posting.key("charge", [Nat.toText(a), "interest-fee", Nat.toText(EOD)])) else {
    Debug.print("no interest-fee posting for account " # Nat.toText(a));
    assert false; loop {};
  };
  let ?v = JCore.postingView(w1000.js, w1000.jb, idx) else { assert false; loop {} };
  assert (v.record.legs.size() == 2);
  if (v.record.legs[0].amount != expected) {
    Debug.print("account " # Nat.toText(a) # " accrued " # Nat.toText(accrued.amount)
      # ", so a tenth of it is " # Nat.toText(expected) # ", but the charge posted "
      # Nat.toText(v.record.legs[0].amount));
    assert false;
  };
  // and it credited fee income, not something that merely balances
  assert (Text.equal(v.record.legs[1].account, "4100"));
  assert (v.record.legs[1].side == #credit);
  chargeChecks += 1;
};
Debug.print("count: percent-of-interest charges equal to a tenth of job 1's accrual = " # Nat.toText(chargeChecks));
assert (chargeChecks == 5);

// 2. the delinquency band reflects what job 3 left due, and 3. the provision is the
//    band's declared percentage of the exposure — both read back through the public
//    loan position, which recomputes from the schedule and the journal.
let overdueFrom = day(2026, 2, 5);          // the first instalment, never paid
// the instalment falling due today, which job 3 moved into the borrower's receivable and
// which is therefore due but not yet late
let our_due_instalment = switch (ProductCore.schedule(w1000.bs.product, Core.productBlocks(w1000.bb),
  switch (ProductCore.get(w1000.bs.product, Core.productBlocks(w1000.bb), w1000.loans[0])) { case (?a) a; case null { assert false; loop {} } })) {
  case (?sv) {
    var amount = 0;
    for (r in sv.rows.vals()) { if (r.dueDate == EOD) amount := r.principal + r.interest + r.fees };
    amount
  };
  case null { assert false; loop {} };
};
assert (our_due_instalment > 0);
Debug.print("the instalment that fell due today is " # Nat.toText(our_due_instalment));
var bandChecks = 0;
for (a in firstFew(w1000.loans, 5).vals()) {
  let pos = switch (Core.loanPosition(w1000.bs, w1000.bb, w1000.js, a, EOD)) {
    case (#ok(v)) v;
    case (#err(e)) { Debug.print(debug_show (e)); assert false; loop {} };
  };
  // Three instalments have fallen due and none was paid — 5 February, 5 March, and the
  // one job 3 moved to due this very morning — but only two of them are **late**. The
  // borrower has today to pay today's instalment, so it is in `dueToDate` and not in the
  // arrears, and the age is measured from the oldest that did pass its date.
  assert (pos.instalmentsOverdue == 2);
  assert (pos.repaid == 0);
  assert (pos.overdueTotal < pos.dueToDate);
  assert (pos.dueToDate - pos.overdueTotal == our_due_instalment);
  assert (pos.overdueDays == EOD - overdueFrom);
  assert (pos.overdueDays == 59);
  assert (pos.band == ?"31-60");
  assert (pos.stage == ?2);
  // the provision the band declares: a fifth of the exposure, half-even
  let want = I.round({ numerator = pos.exposure * 20; denominator = 100; negative = false }, #halfEven).amount;
  if (pos.requiredProvision != want) {
    Debug.print("loan " # Nat.toText(a) # ": exposure " # Nat.toText(pos.exposure)
      # " at 20% is " # Nat.toText(want) # " but the rule required " # Nat.toText(pos.requiredProvision));
    assert false;
  };
  // and the run posted exactly that, so job 5 acted on job 4's band
  if (pos.carriedAllowance != pos.requiredProvision) {
    Debug.print("loan " # Nat.toText(a) # " carries " # Nat.toText(pos.carriedAllowance)
      # " against a requirement of " # Nat.toText(pos.requiredProvision));
    assert false;
  };
  assert (pos.requiredProvision > 0);
  bandChecks += 1;
};
Debug.print("count: loans whose band and provision agree by value = " # Nat.toText(bandChecks));
assert (bandChecks == 5);

// the band really is the one the overdue days select, and not a constant: the same
// account read a day before the first instalment was due is current and provided at 1%
let earlyPos = switch (Core.loanPosition(w1000.bs, w1000.bb, w1000.js, w1000.loans[0], overdueFrom - 1)) {
  case (#ok(v)) v;
  case (#err(e)) { Debug.print(debug_show (e)); assert false; loop {} };
};
assert (earlyPos.overdueDays == 0);
assert (earlyPos.band == ?"current");
assert (earlyPos.stage == ?1);
// and performing exposure is provided for at the rate the product declared for it,
// which is a different rate from the one the same loan attracts today
let earlyWant = I.round({ numerator = earlyPos.exposure; denominator = 100; negative = false }, #halfEven).amount;
assert (earlyPos.requiredProvision == earlyWant);
assert (earlyPos.requiredProvision > 0);
Debug.print("count: band readings that differ with the date = 2");

// ═══════════════════════════════════════════════════════════════════════════
//  E13 — the statement cut is a record, not a re-derivation
// ═══════════════════════════════════════════════════════════════════════════

let cutAccount = w1000.curs[0];
let ?cutBefore = BatchCore.cutFor(w1000.bs.batch, cutAccount) else { Debug.print("no cut"); assert false; loop {} };
assert (cutBefore.day == EOD);
assert (cutBefore.movements > 0);
// the run is complete, so a back-valued posting into the cut day is admitted again
ignore w1000.post(#depositToAccount({
  account = cutAccount; amount = 777_00; postingDate = EOD; valueDate = EOD - 3;
  period = "2026-04"; narration = "a late deposit, value dated into the cut"; funding = #glAccount("1999");
}));
let ?cutAfter = BatchCore.cutFor(w1000.bs.batch, cutAccount) else { assert false; loop {} };
assert (cutAfter.openingDebits == cutBefore.openingDebits);
assert (cutAfter.openingCredits == cutBefore.openingCredits);
assert (cutAfter.closingDebits == cutBefore.closingDebits);
assert (cutAfter.closingCredits == cutBefore.closingCredits);
assert (cutAfter.movements == cutBefore.movements);
// while the live balance did move, so the comparison above is not comparing two
// unchanged things
let live = JCore.valueDatedBalance(w1000.js, "2110", ?Posting.subledgerOf(
  switch (ProductCore.get(w1000.bs.product, Core.productBlocks(w1000.bb), cutAccount)) { case (?e) e.identifier; case null { assert false; loop {} } }
), "EGP", EOD);
assert (live.credits > cutAfter.closingCredits);
Debug.print("count: statement cuts unchanged by later back-valued activity = 1");

// ═══════════════════════════════════════════════════════════════════════════
//  E2 — interruption is survivable at every chunk boundary
// ═══════════════════════════════════════════════════════════════════════════

// The portfolio here is small and the shard size is 1, which gives a boundary between
// every pair of items — many more boundaries than a realistic shard size would, and each
// one a place the canister could have stopped. The reference run does the same work in
// as few chunks as the advance limit allows.
//
// What must match is the **journal**: the money, and the keys it was posted under. The
// bank's own log legitimately differs — a run stopped and resumed records more chunk
// blocks than one that was not — and that difference is the evidence of the interruption
// rather than a discrepancy.
let smallSpec : Spec = { curs = 4; savs = 5; loans = 3; fds = 2; usds = 2; dry = 2; instructions = 2; failing = 0; openTill = false; periods = months; activate = true };

let reference = build(smallSpec);
ignore workWhole(reference, 1, Batch.MAX_ADVANCE_LIMIT);
let refRun = runOf(reference);
assert (BatchCore.failureCount(refRun) == 0);
let refFingerprint = JCore.fingerprint(reference.js);
let refKeys = postingKeys(reference.js, reference.jb);
let refDigest = postingDigest(reference.js, reference.jb);
// an item is a walk of one account (or one row) per chunk at shard size 1, so a chunk of one item is one step of one
// walk: the boundaries are every such step — counted once on a probe world driven one step at a time
let probe = build(smallSpec);
ignore probe.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 1 }));
var boundaries = 0;
label steps loop { let a = probe.advance(1); boundaries += 1; if (a.completed) break steps };
assert (BatchCore.isComplete(runOf(probe)));
Debug.print("count: chunk boundaries in the interrupted run = " # Nat.toText(boundaries - 1));
assert (boundaries - 1 >= 40);

var boundariesChecked = 0;
var resumedAdvances = 0;
var stop = 1;
while (stop < boundaries) {
  let w = build(smallSpec);
  ignore w.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 1 }));
  // work up to the boundary one step at a time, which is what makes the stop exact: a step advances the item cursor
  // or the item, never neither
  var done = 0;
  while (done < stop) {
    let before = runOf(w).cursor;
    let beforeSub = runOf(w).itemCursor;
    let a = w.advance(1);
    assert (a.cursorTo >= a.cursorFrom);
    assert (runOf(w).cursor > before or runOf(w).itemCursor != beforeSub or a.completed);
    assert (not a.completed or done == boundaries - 1);
    done += 1;
  };
  assert (not BatchCore.isComplete(runOf(w)));
  // … and then resume, as a restarted canister would
  resumedAdvances += workOpen(w, Batch.MAX_ADVANCE_LIMIT);
  let r = runOf(w);
  assert (r.cursor == r.items);
  assert (BatchCore.isComplete(r));
  assert (BatchCore.failureCount(r) == 0);
  // the same money, the same keys, the same journal
  if (r.posted != refRun.posted or r.examined != refRun.examined or r.zeroMovement != refRun.zeroMovement) {
    Debug.print("stopping at boundary " # Nat.toText(stop) # " changed the totals: posted "
      # Nat.toText(r.posted) # " examined " # Nat.toText(r.examined) # " zero " # Nat.toText(r.zeroMovement));
    assert false;
  };
  let keys = postingKeys(w.js, w.jb);
  if (keys.size() != refKeys.size()) {
    Debug.print("stopping at boundary " # Nat.toText(stop) # " made " # Nat.toText(keys.size())
      # " postings, not " # Nat.toText(refKeys.size()));
    assert false;
  };
  var k = 0;
  while (k < keys.size()) {
    if (keys[k] != refKeys[k]) { Debug.print("boundary " # Nat.toText(stop) # ": posting key " # Nat.toText(k) # " differs"); assert false };
    k += 1;
  };
  if (not Text.equal(postingDigest(w.js, w.jb), refDigest)) { Debug.print("boundary " # Nat.toText(stop) # ": the legs differ"); assert false };
  if (JCore.fingerprint(w.js) != refFingerprint) { Debug.print("boundary " # Nat.toText(stop) # ": the journal state differs"); assert false };
  // the bank log does differ, and that is the interruption showing
  assert (r.chunks > refRun.chunks);
  boundariesChecked += 1;
  stop += 1;
};
Debug.print("count: chunk boundaries stopped and resumed with an identical journal = " # Nat.toText(boundariesChecked));
assert (boundariesChecked == boundaries - 1);
Debug.print("count: advances used resuming = " # Nat.toText(resumedAdvances));

// ═══════════════════════════════════════════════════════════════════════════
//  E3 — a retried chunk posts nothing new
// ═══════════════════════════════════════════════════════════════════════════

// The crash window is narrower than a chunk boundary: the postings land and the block
// that records the chunk does not. A canister that stops there comes back with the money
// moved and the cursor where it was, and re-derives the same chunk. Every posting it then
// makes must be recognised as the one already there — by its derived key, and with its
// legs read back and compared — so the money moves once.
let e3 = build(smallSpec);
ignore e3.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }));
let heightBefore = JCore.height(e3.js);
let lost = e3.advanceLosingBankBlocks(Batch.MAX_ADVANCE_LIMIT);
assert (lost.posted > 0);
assert (lost.postings.size() > 0);
let heightAfterPostings = JCore.height(e3.js);
assert (heightAfterPostings > heightBefore);
// the cursor did not move, because the block that would have moved it was lost
assert (runOf(e3).cursor == 0);
assert (runOf(e3).posted == 0);

let replayed = e3.advance(Batch.MAX_ADVANCE_LIMIT);
// Not one new block in the journal. The run is idempotent by two distinct mechanisms and
// both are exercised here:
//
//   * **by key** — the job derives the same idempotency key, the journal answers
//     `#duplicate`, and the run reads the named block and checks leg for leg that it is
//     the posting the job intended. Those postings come back as indices the first attempt
//     made.
//   * **by convergence** — a job that brings a balance to a target figure (the maturity
//     interest a deposit is entitled to, the allowance a band requires) finds the figure
//     already there and posts nothing at all, so it names no block. That is the same
//     outcome reached the other way, and it is why the replay may name fewer blocks than
//     the first attempt rather than exactly the same ones.
//
// What neither mechanism may do is move money twice, which is what the height and the
// posted count below say.
assert (JCore.height(e3.js) == heightAfterPostings);
assert (replayed.posted == 0);
assert (replayed.postings.size() > 0);
assert (replayed.postings.size() <= lost.postings.size());
var replayChecks = 0;
var pi = 0;
while (pi < replayed.postings.size()) {
  // every block the replay named is one the first attempt made
  var found = false;
  for (x in lost.postings.vals()) { if (x == replayed.postings[pi]) found := true };
  if (not found) {
    Debug.print("the replay named block " # Nat.toText(replayed.postings[pi]) # ", which the first attempt did not make");
    assert false;
  };
  // and the block it named is a posting whose legs balance
  let ?v = JCore.postingView(e3.js, e3.jb, replayed.postings[pi]) else { Debug.print("not a posting"); assert false; loop {} };
  var debits = 0;
  var credits = 0;
  for (l in v.record.legs.vals()) { if (l.side == #debit) debits += l.amount else credits += l.amount };
  assert (debits == credits and debits > 0);
  replayChecks += 1;
  pi += 1;
};
Debug.print("count: postings the first attempt made = " # Nat.toText(lost.postings.size()));
Debug.print("count: duplicates whose named block was read and matched = " # Nat.toText(replayChecks));
Debug.print("count: postings the replay converged on and did not repeat = " # Nat.toText(lost.postings.size() - replayChecks));
assert (replayChecks > 0);
// and the examined totals are the same work done twice, which is what a replay is
assert (replayed.examined == lost.examined);
assert (replayed.completed == lost.completed);
inspectFailures(runOf(e3));

// ═══════════════════════════════════════════════════════════════════════════
//  E4 — a duplicate naming the wrong block is refused
// ═══════════════════════════════════════════════════════════════════════════

// A posting already exists under the key the charge job will derive, and it is not the
// charge: the job must refuse rather than read it as its own work done.
let e4 = build(smallSpec);
let victim = e4.curs[0];
let ?victimEntry = ProductCore.get(e4.bs.product, Core.productBlocks(e4.bb), victim) else { assert false; loop {} };
let collidingKey = Posting.key("charge", [Nat.toText(victim), "ledger-fee", Nat.toText(EOD)]);
let impostor : JT.PostingInput = {
  idempotencyKey = collidingKey;
  postingDate = EOD; valueDate = EOD; period = "2026-04";
  legs = [
    Posting.leg("1999", null, #debit, "EGP", 42_00),
    Posting.leg("4100", null, #credit, "EGP", 42_00),
  ];
  sourceRef = { kind = "impostor"; id = "e4" };
  narration = "not the charge, but under its key";
  correctionOf = null;
};
let impostorIndex = switch (JCore.preparePost(e4.js, bankP, clock, impostor)) {
  case (#ok(#event(ev))) e4.jraw(ev).index;
  case (other) { Debug.print("the impostor could not be posted: " # debug_show (other)); assert false; loop {} };
};
assert (JCore.postingIndexByKey(e4.js, bankP, collidingKey) == ?impostorIndex);

ignore workWhole(e4, 4, Batch.MAX_ADVANCE_LIMIT);
let r4 = runOf(e4);
// the run finished and the cursor reached the end: one job refusing does not stop it
assert (r4.cursor == r4.items);
assert (BatchCore.isComplete(r4));
// The refusal is typed and it names the block that already holds the key. Which of the
// two guards speaks is itself worth recording: the journal refuses a key reused with
// different content before it ever reports a duplicate, so the reason here is
// `#IdempotencyKeyReused` and not the run's own leg comparison. Both are asserted, so a
// change on either side of that boundary shows up as a failing test rather than as a
// silently accepted impostor.
var namedWrongBlock = 0;
for (f in BatchCore.failuresOf(r4).vals()) {
  if (Text.equal(f.entity, Nat.toText(victim))) {
    assert (Text.contains(f.error, #text (debug_show (impostorIndex))));
    assert (Text.contains(f.error, #text "IdempotencyKeyReused")
      or Text.contains(f.error, #text "does not carry the legs this job intended"));
    assert (f.job == #charges);
    namedWrongBlock += 1;
  };
};
Debug.print("count: jobs that refused a duplicate naming the wrong block = " # Nat.toText(namedWrongBlock));
assert (namedWrongBlock == 1);
// and the impostor was not mistaken for the charge: nothing credited fee income under
// that key beyond the 42.00 it already carried
let ?impostorView = JCore.postingView(e4.js, e4.jb, impostorIndex) else { assert false; loop {} };
assert (impostorView.record.legs[1].amount == 42_00);
inspectFailures(r4);

// ═══════════════════════════════════════════════════════════════════════════
//  E5 — inputs cannot move under a run
// ═══════════════════════════════════════════════════════════════════════════

// The plan was fixed at the opening block and the jobs read balances as they go, so a
// posting value-dated into the day the run is working would change the answer underneath
// it. One is refused while the run is open and admitted once it is closed; a posting
// value-dated after the run's date never touches it and is admitted throughout.
let e5 = build(smallSpec);
let e5Account = e5.savs[0];
func backValued(vd : JT.Day, amount : Nat) : T.Command {
  #depositToAccount({
    account = e5Account; amount; postingDate = EOD; valueDate = vd;
    period = "2026-04"; narration = "a deposit value dated " # dtext(vd); funding = #glAccount("1999");
  })
};
// 5 April is a Sunday, 4 and 3 April are the rest days, 2 April is the business day
// before it: the product's convention is `sameDay`, so the dates used here are business
// days and the refusals below are the run's and not the calendar's.
assert (not Conv.isBusinessDay(?calConfig, EOD - 1));
assert (Conv.isBusinessDay(?calConfig, EOD - 3));
assert (Conv.isBusinessDay(?calConfig, EOD - 31));
assert (Conv.isBusinessDay(?calConfig, EOD + 1));
// before the run opens, the same posting is admitted — so the refusal below is the run's
ignore e5.post(backValued(EOD - 3, 11_00));
ignore e5.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }));

// on the run's own date, and before it: refused, with the run named, and nothing moves
e5.refuseUnmoved(backValued(EOD, 12_00), "RunOpenForDate");
e5.refuseUnmoved(backValued(EOD - 3, 13_00), "RunOpenForDate");
e5.refuseUnmoved(backValued(EOD - 31, 14_00), "RunOpenForDate");
Debug.print("count: postings refused while the run is open = 3");
// and the refusal names the date the run is for, not merely that one exists
switch (Core.planCommand(e5.bs, e5.bb, e5.js, e5.jb, bankP, clock, backValued(EOD, 15_00), 9_000_001)) {
  case (#err(e)) {
    let got = debug_show (e);
    // `debug_show` groups digits, so the date is matched in the form the error prints
    assert (Text.contains(got, #text (debug_show (EOD))));
    assert (Text.contains(got, #text "BR01"));
  };
  case (#ok(_)) { Debug.print("a posting was admitted under an open run"); assert false };
};

// after the run's date: admitted, because no job of this run will read it
let afterIndices = e5.post(backValued(EOD + 1, 16_00));
assert (afterIndices.size() == 1);
switch (JCore.postingView(e5.js, e5.jb, afterIndices[0])) {
  case (?v) { assert (v.record.valueDate == EOD + 1); assert (v.record.valueDateRequested == null) };
  case null assert false;
};
Debug.print("count: postings after the run's date admitted while it is open = 1");

// once the run has completed, the back-valued posting is admitted
ignore workOpen(e5, Batch.MAX_ADVANCE_LIMIT);
assert (BatchCore.isComplete(runOf(e5)));
let backIndices = e5.post(backValued(EOD - 3, 17_00));
assert (backIndices.size() == 1);
switch (JCore.postingView(e5.js, e5.jb, backIndices[0])) {
  case (?v) assert (v.record.valueDate == EOD - 3);
  case null assert false;
};
Debug.print("count: back-valued postings admitted once the run completed = 1");
inspectFailures(runOf(e5));

// ═══════════════════════════════════════════════════════════════════════════
//  E6 — a failing item does not stop the queue
// ═══════════════════════════════════════════════════════════════════════════

// Twelve standing instructions paid out of accounts that hold nothing, and a till nobody
// settled: thirteen items that cannot succeed. The run must finish anyway, record each
// one, apply the declared retry limit and then park — and the period close must refuse
// while any of them is unresolved.
// April is declared as the single business day the run is for, because the accrual
// cut-off is satisfied only when every business day of the period has an accrual and a
// run covers one day. Nothing in this battery posts into 1–4 or 6–30 April.
let closingPeriods : [(Text, JT.Day, JT.Day)] = [months[0], months[1], months[2], ("2026-04", EOD, EOD)];
let e6 = build({ curs = 3; savs = 4; loans = 2; fds = 2; usds = 2; dry = 12; instructions = 2; failing = 12; openTill = true; periods = closingPeriods; activate = true });
ignore e6.cmd(#setRetryPolicy({ policy = { book = "BR01"; limit = 2 } }));
assert (BatchCore.retryLimit(e6.bs.batch, "BR01") == 2);
// a limit beyond the bound is refused, so the retry count is not a way to loop for ever
e6.refuse(#setRetryPolicy({ policy = { book = "BR01"; limit = 17 } }), "InvalidRetryPolicy");

// one item at a time, so the run has many advances in which to re-attempt what failed
let e6Advances = workWhole(e6, 1, 1);
let r6 = runOf(e6);
assert (BatchCore.isComplete(r6));
assert (r6.cursor == r6.items);
Debug.print("count: advances the failing run took = " # Nat.toText(e6Advances));
Debug.print("count: items in the failing run = " # Nat.toText(r6.items));
Debug.print("count: failures the failing run carries = " # Nat.toText(BatchCore.failureCount(r6)));
assert (BatchCore.failureCount(r6) >= 13);

// every failure is typed, named and attributed to a job, and none is a zero-amount leg
inspectFailures(r6);
var instructionFailures = 0;
var tillFailures = 0;
var maxAttempts = 0;
for (f in BatchCore.failuresOf(r6).vals()) {
  if (f.job == #standingInstructions) instructionFailures += 1;
  if (f.job == #tillCheck) tillFailures += 1;
  if (f.attempts > maxAttempts) maxAttempts := f.attempts;
  // the declared limit is a ceiling, never exceeded
  assert (f.attempts <= 2);
  assert (f.attempts >= 1);
};
Debug.print("count: standing instructions that could not be paid = " # Nat.toText(instructionFailures));
Debug.print("count: tills left unsettled at close = " # Nat.toText(tillFailures));
Debug.print("count: the highest attempt count any failure reached = " # Nat.toText(maxAttempts));
assert (instructionFailures == 12);
assert (tillFailures == 1);
assert (maxAttempts == 2);          // retried up to the declared limit, then parked

// the run still did the work it could: the payable instructions were paid
var paid = 0;
for (j in [0, 1].vals()) {
  let key = Posting.key("standing-instruction", ["si-ok-" # Nat.toText(j), Nat.toText(EOD)]);
  if (JCore.postingIndexByKey(e6.js, bankP, key) != null) paid += 1;
};
Debug.print("count: standing instructions the run paid despite the failures = " # Nat.toText(paid));
assert (paid == 2);

// and the close refuses while any failure is unresolved
assert (BatchCore.unresolvedFailures(e6.bs.batch, "BR01", EOD, EOD) == BatchCore.failureCount(r6));
ignore e6.cmd(#openPeriodEnd({ book = "BR01"; period = "2026-04" }));
ignore e6.cmd(#recordClosingRates({ book = "BR01"; period = "2026-04" }));
ignore e6.cmd(#markAccrualComplete({ book = "BR01"; period = "2026-04" }));
ignore e6.cmd(#revaluePositions({ book = "BR01"; period = "2026-04"; postingDate = EOD; narration = "revaluation" }));
ignore e6.cmd(#amortisePeriodDeferrals({ book = "BR01"; period = "2026-04"; postingDate = EOD; narration = "amortisation" }));
e6.refuse(#reconcilePeriod({ book = "BR01"; period = "2026-04" }), "UnresolvedFailures");
Debug.print("count: period closes refused while failures are unresolved = 1");

// A sign-off is recorded, not assumed: one for a failure the run is not carrying is
// refused, and one with no reason given is refused.
let carried = BatchCore.failuresOf(r6);
e6.refuse(#resolveBatchFailure({ book = "BR01"; businessDate = EOD; item = 9_999; entity = "nobody"; justification = "x" }), "UnknownFailure");
e6.refuse(#resolveBatchFailure({ book = "BR01"; businessDate = EOD; item = carried[0].item; entity = carried[0].entity; justification = "" }), "InvalidJustification");
Debug.print("count: sign-offs refused = 2");

// worked one by one, as an operations team works an exception report
for (f in carried.vals()) {
  ignore e6.cmd(#resolveBatchFailure({
    book = "BR01"; businessDate = EOD; item = f.item; entity = f.entity;
    justification = "worked on the exception report: " # f.error;
  }));
};
assert (BatchCore.failureCount(runOf(e6)) == 0);
assert (BatchCore.unresolvedFailures(e6.bs.batch, "BR01", EOD, EOD) == 0);
// the same sign-off twice is refused, because the failure is no longer there to sign off
e6.refuse(#resolveBatchFailure({ book = "BR01"; businessDate = EOD; item = carried[0].item; entity = carried[0].entity; justification = "again" }), "UnknownFailure");
Debug.print("count: failures signed off = " # Nat.toText(carried.size()));
// and the close goes on
ignore e6.cmd(#reconcilePeriod({ book = "BR01"; period = "2026-04" }));
Debug.print("count: period closes that proceeded once the report was worked = 1");

// A failure the batch can repair itself is repaired by the retry rather than signed off.
// The cause here is configuration and not a posting — an overdraft facility, which the
// value-date gate does not touch — so it can be fixed while the run is still open, which
// is exactly the case the retry pass exists for.
let e6b = build({ curs = 3; savs = 4; loans = 0; fds = 0; usds = 0; dry = 2; instructions = 1; failing = 2; openTill = false; periods = months; activate = true });
ignore e6b.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 1 }));
// work until the instruction items have failed
var firstFailure = 0;
while (BatchCore.failureCount(runOf(e6b)) == 0 and firstFailure < 400) {
  ignore e6b.advance(1);
  firstFailure += 1;
};
let failedRun = runOf(e6b);
assert (BatchCore.failureCount(failedRun) > 0);
let badFailure = BatchCore.failuresOf(failedRun)[0];
assert (badFailure.job == #standingInstructions);
Debug.print("the run could not pay " # badFailure.entity # " and recorded it");
// operations grant the facility the payer needed
ignore e6b.cmd(#grantFacility({ account = e6b.dry[0]; limit = 1_000_00 }));
// the next advance re-attempts it, and only it
let repair = e6b.advance(1);
Debug.print("count: failures the retry pass resolved = " # Nat.toText(repair.resolved.size()));
assert (repair.resolved.size() == 1);
assert (Text.equal(repair.resolved[0].entity, badFailure.entity));
assert (repair.posted > 0);
// the instruction really was paid, under the key the job derives
let ?repaired = JCore.postingIndexByKey(e6b.js, bankP, Posting.key("standing-instruction", [badFailure.entity, Nat.toText(EOD)])) else {
  Debug.print("the repaired instruction posted nothing");
  assert false; loop {};
};
let ?repairedView = JCore.postingView(e6b.js, e6b.jb, repaired) else { assert false; loop {} };
assert (repairedView.record.legs.size() == 2);
assert (repairedView.record.legs[0].amount == 500_00);
// and the failure is gone from the run, so it no longer blocks the close
var stillThere = false;
for (f in BatchCore.failuresOf(runOf(e6b)).vals()) {
  if (f.item == badFailure.item and Text.equal(f.entity, badFailure.entity)) stillThere := true;
};
assert (not stillThere);
Debug.print("count: failures repaired by the retry rather than signed off = 1");
ignore workOpen(e6b, Batch.MAX_ADVANCE_LIMIT);

// ═══════════════════════════════════════════════════════════════════════════
//  E15 — the gate is a height
// ═══════════════════════════════════════════════════════════════════════════

// A world with the accounts and the products in place and every money-visible feature
// still off. Nothing an administrator can say turns the batch on: the only thing that
// does is an activation height, recorded as a block, and the run is refused until every
// feature its plan would post under is past one.
// First, a world with nothing in it and every feature still where it starts: off. The
// batch refuses to open a run at all, naming its own gate.
let e15off = build({ curs = 0; savs = 0; loans = 0; fds = 0; usds = 0; dry = 0; instructions = 0; failing = 0; openTill = false; periods = months; activate = false });
var featuresOff = 0;
for (f in ProdT.featureIds().vals()) {
  assert (Core.featureActivation(e15off.bs, f) == T.ACTIVATION_OFF);
  assert (not Core.featureActive(e15off.bs, f));
  featuresOff += 1;
};
Debug.print("count: money-visible features off by default = " # Nat.toText(featuresOff));
assert (featuresOff == 9);
assert (Text.equal(ProdT.FEATURE_END_OF_DAY, "batch.endOfDay"));

switch (Core.planCommand(e15off.bs, e15off.bb, e15off.js, e15off.jb, bankP, clock, #openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }), 8_000_001)) {
  case (#err(#FeatureInactive(d))) {
    assert (Text.equal(d.feature, ProdT.FEATURE_END_OF_DAY));
    assert (d.activationHeight == T.ACTIVATION_OFF);
    Debug.print("the run refused below the gate, naming " # d.feature);
  };
  case (other) { Debug.print(debug_show (other)); assert false };
};
// transferring the bank's administration does not activate anything: there is no flag
ignore e15off.cmd(#transferBankAdmin({ admin = installer }));
assert (not Core.featureActive(e15off.bs, ProdT.FEATURE_END_OF_DAY));
e15off.refuse(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }), "FeatureInactive");
Debug.print("administrative acts that activated the batch: none; transferring the admin left it off");

// Then a populated world, with each gate raised to a height the bank has not reached.
// That is the same refusal arriving by the other route — a height in the future rather
// than no height at all — and it names the features the plan's jobs would post under, one
// at a time, so a partially activated deployment is told exactly what is missing.
let e15 = build({ curs = 3; savs = 3; loans = 2; fds = 2; usds = 2; dry = 2; instructions = 0; failing = 0; openTill = true; periods = months; activate = true });
let unreachable : Nat64 = Nat64.fromNat(Core.height(e15.bs)) + 1_000_000;
let gateOrder = [ProdT.FEATURE_END_OF_DAY, ProdT.FEATURE_INTEREST, ProdT.FEATURE_CHARGES, ProdT.FEATURE_CREDIT, ProdT.FEATURE_TILL];
for (f in gateOrder.vals()) {
  ignore e15.cmd(#setFeatureActivation({ feature = f; height = unreachable }));
  assert (not Core.featureActive(e15.bs, f));
};
var gatesNamed = 0;
for (f in gateOrder.vals()) {
  switch (Core.planCommand(e15.bs, e15.bb, e15.js, e15.jb, bankP, clock, #openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }), 8_000_100 + gatesNamed)) {
    case (#err(#FeatureInactive(d))) {
      if (not Text.equal(d.feature, f)) { Debug.print("expected " # f # " to be named, got " # d.feature); assert false };
      assert (d.activationHeight == unreachable);
      assert (d.height < d.activationHeight);
    };
    case (other) { Debug.print("expected " # f # " to be refused, got " # debug_show (other)); assert false };
  };
  ignore e15.cmd(#setFeatureActivation({ feature = f; height = Nat64.fromNat(Core.height(e15.bs)) }));
  gatesNamed += 1;
};
Debug.print("count: gates the run named before it would open = " # Nat.toText(gatesNamed));
assert (gatesNamed == 5);

// with every feature its plan needs past a height, the run opens and works
ignore e15.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }));
let beforeRun15 = JCore.height(e15.js);
ignore workOpen(e15, Batch.MAX_ADVANCE_LIMIT);
assert (JCore.height(e15.js) > beforeRun15);
let r15 = runOf(e15);
assert (BatchCore.isComplete(r15));
assert (r15.posted > 0);
inspectFailures(r15);
Debug.print("count: postings the batch made once every gate was past a height = " # Nat.toText(r15.posted));

// and the activation is a block, not a setting: the height it carries is readable back
assert (Core.featureActivation(e15.bs, ProdT.FEATURE_END_OF_DAY) != T.ACTIVATION_OFF);
assert (Core.featureActivation(e15.bs, ProdT.FEATURE_END_OF_DAY) <= Nat64.fromNat(Core.height(e15.bs)));
Debug.print("count: activations readable back from the log = 1");

// ═══════════════════════════════════════════════════════════════════════════
//  E10 — an open advance path cannot choose content
// ═══════════════════════════════════════════════════════════════════════════

// The argument list is the whole argument: `advanceEndOfDay(book, businessDate, limit)`
// carries a book, a date and how much work to do, and no content of any kind. There is no
// amount, no account, no leg, no job selector — so the only thing a caller chooses is
// whether progress happens. What it does is fixed by the plan the opening block hashed,
// which the advance re-derives and checks before it touches anything.
let e10 = build({ curs = 3; savs = 3; loans = 2; fds = 2; usds = 2; dry = 2; instructions = 2; failing = 0; openTill = false; periods = months; activate = true });
ignore e10.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }));

// the limit is bounded at both ends, so an advance can neither do nothing nor run away
switch (e10.tryAdvance(0)) {
  case (#err(e)) assert (Text.contains(debug_show (e), #text "AdvanceLimit"));
  case (#ok(_)) { Debug.print("a zero limit was accepted"); assert false };
};
switch (e10.tryAdvance(Batch.MAX_ADVANCE_LIMIT + 1)) {
  case (#err(e)) assert (Text.contains(debug_show (e), #text "AdvanceLimit"));
  case (#ok(_)) { Debug.print("a limit beyond the bound was accepted"); assert false };
};
Debug.print("count: advance limits refused = 2");

// it cannot skip: the cursor moves by exactly what the limit allows, never further
let step = e10.advance(3);
assert (step.cursorFrom == 0 and step.cursorTo == 3);
assert (runOf(e10).cursor == 3);
let step2 = e10.advance(2);
assert (step2.cursorFrom == 3 and step2.cursorTo == 5);
Debug.print("count: advances that moved the cursor by exactly their limit = 2");

// a run for a date that has none, and a run already complete, are both refused
switch (Core.runEndOfDayChunk(e10.bs, e10.bb, e10.js, e10.jb, bankP, clock, "BR01", EOD + 1, 4, { bank = func(_) { 0 }; journal = func(_) { 0 }; monitor = Core.noMonitor })) {
  case (#err(e)) assert (Text.contains(debug_show (e), #text "UnknownRun"));
  case (#ok(_)) { Debug.print("an advance was planned for a date with no run"); assert false };
};
ignore workOpen(e10, Batch.MAX_ADVANCE_LIMIT);
switch (e10.tryAdvance(4)) {
  case (#err(e)) assert (Text.contains(debug_show (e), #text "RunComplete"));
  case (#ok(_)) { Debug.print("a completed run was advanced again"); assert false };
};
Debug.print("count: advances refused outside an open run = 2");

// the postings are exactly the plan's: the same journal a run worked in one chunk
// produced, which E1 already compared across shard sizes, and every one of them is
// attributed to the canister rather than to whoever advanced the run
var attributedToCanister = 0;
var attributedElsewhere = 0;
var hi = 0;
while (hi < JCore.height(e10.js)) {
  switch (JCore.postingView(e10.js, e10.jb, hi)) {
    case (?v) {
      if (Principal.equal(v.caller, bankP)) attributedToCanister += 1 else attributedElsewhere += 1;
    };
    case null {};
  };
  hi += 1;
};
Debug.print("count: postings attributed to the canister = " # Nat.toText(attributedToCanister));
assert (attributedToCanister > 0);
assert (attributedElsewhere == 0);

// and the administrative acts around the run are permissioned while the advance is not:
// opening one, setting the retry policy, defining an instruction and signing off an
// exception each require a permission, and all four are dual-authorised by default
var batchPermissions = 0;
for (c in ["openEndOfDay", "setRetryPolicy", "defineStandingInstruction", "cancelStandingInstruction", "resolveBatchFailure"].vals()) {
  let ?perm = P.byCommandName(c) else { Debug.print(c # " has no permission"); assert false; loop {} };
  assert (perm.dualByDefault);
  batchPermissions += 1;
};
Debug.print("count: batch commands behind a permission = " # Nat.toText(batchPermissions));
assert (batchPermissions == 5);
// while the advance itself is an open method with a stated reason, and guards nothing
assert (P.byMethod("advanceEndOfDay") == null);
var openReason = "";
for ((m, reason) in P.openMethods().vals()) { if (Text.equal(m, "advanceEndOfDay")) openReason := reason };
assert (Text.size(openReason) > 0);
assert (Text.contains(openReason, #text "cannot choose"));
Debug.print("count: open advance methods with a stated reason = 1");

// ─── the battery's own invariant ─────────────────────────────────────────────

Debug.print("count: batch failures inspected across the battery = " # Nat.toText(failuresSeen));
Debug.print("batch failures that were a zero-amount leg: " # Nat.toText(zeroLegFailures) # " — a job that would post nothing counts zero movement instead");
assert (failuresSeen > 0);
assert (zeroLegFailures == 0);

// ═══════════════════════════════════════════════════════════════════
//  ALERTS — step 5 of the index component: the monitoring job and the review
// ═══════════════════════════════════════════════════════════════════
//
// What is proved: a book with no end-of-day rule plans exactly as before (every world above); with
// one, the plan gains a monitoring shard per product, the job examines every account, opens one
// alert per finding, never a secondA for the same finding (a re-derived chunk afterA the bank's
// blocks were lostA opens nothing new), and records an evaluation refused for its bound as a
// failure rather than as nothing found; the review is dual-authorised, once, and the report
// reference is carried by the escalation block.

let eA = build({ curs = 3; savs = 3; loans = 2; fds = 2; usds = 2; dry = 2; instructions = 0; failing = 0; openTill = false; periods = months; activate = true });
// the monitoring item is in the plan whether a rule exists or not (a plan is a function of the registry, never of
// what happens to be defined on the day — the audit of 13 September, finding B1); the item examines nothing until a
// rule exists, and the same plan holds after one is defined the dual way
let planNoRule = switch (Batch.plan(Core.planInput(eA.bs, "BR01", EOD, Core.height(eA.bs), 4))) { case (#ok(xs)) xs; case (#err(_)) { assert false; loop {} } };
var monitoringItems = 0;
for (i in planNoRule.vals()) { if (i.job == #monitoring) { monitoringItems += 1; assert (Batch.jobRank(i.job) == 10) } };
ignore eA.cmd(#defineMonitoringRule({ id = "velocity-1"; currency = null; spec = #velocity({ count = 1; windowDays = 1 }) }));
let planWithRule = switch (Batch.plan(Core.planInput(eA.bs, "BR01", EOD, Core.height(eA.bs), 4))) { case (#ok(xs)) xs; case (#err(_)) { assert false; loop {} } };
assert (monitoringItems > 0 and Batch.planHash(planWithRule) == Batch.planHash(planNoRule));
assert (Batch.inJobOrder(planWithRule));
Debug.print("count: monitoring items planned, one per product, rule or no rule = " # Nat.toText(monitoringItems));

// the evaluation this battery controls: every even account is found (velocity-1 v1, citing the
// account id as its posting), one chosen account is refused as too wide
let wideAccount = eA.curs[0];
let findingFor = func(a : Nat) : MT.Finding { { rule = "velocity-1"; version = 1; account = a; day = EOD; postings = [a]; detail = "test" } };
// every other account has a finding — the parity of the first monitored account, so the first
// monitoring chunk (the one E3 cuts below) always opens an alert whatever block ids the world has
let firstMonitoring = do { var k = 0; label find for (i in planWithRule.vals()) { if (i.job == #monitoring) break find; k += 1 }; k };
let parity = do {
  // the first monitoring item is the first accounts of the first product; one of them, not the
  // wide one, sets the parity
  let item = planWithRule[firstMonitoring];
  var p = 0;
  label pick for (a in ProductCore.accountIdsOfProduct(eA.bs.product, item.product).vals()) { if (a != wideAccount) { p := a % 2; break pick } };
  p
};
func flagged(a : Nat) : Bool { a % 2 == parity };
monitorHook := func(a : Nat, d : Nat) : Result.Result<[MT.Finding], MT.MonitoringError> {
  assert (d == EOD);
  if (a == wideAccount) return #err(#TooWide({ rule = "velocity-1"; size = 3; bound = 2 }));
  if (flagged(a)) #ok([findingFor(a)]) else #ok([])
};
ignore eA.cmd(#openEndOfDay({ book = "BR01"; businessDate = EOD; shardSize = 4 }));
// run everything up to the monitoring items with the bank's blocks kept, then cut the run in the
// monitoring shards: the first monitoring chunk loses its bank blocks, the chunk is re-derived
var advanced = 0;
while (advanced < firstMonitoring) { let a = eA.advance(Nat.min(4, firstMonitoring - advanced)); advanced := a.cursorTo };
let alertsBefore = AlertCore.counts(eA.bs.alerts).opened;
let lostA = eA.advanceLosingBankBlocks(1);
assert (AlertCore.counts(eA.bs.alerts).opened == alertsBefore);   // nothing of it stayed
// the run's cursorA did not move either, so the same item is worked again, with blocks kept
let redoneA = eA.advance(1);
assert (redoneA.cursorFrom == lostA.cursorFrom);
let openedByFirst = AlertCore.counts(eA.bs.alerts).opened - alertsBefore;
assert (openedByFirst > 0);
// and worked a third time by hand: every finding is already known, so nothing new
for (a in ProductCore.accountIds(eA.bs.product).vals()) {
  if (flagged(a) and a != wideAccount) { assert (Core.alertFor(eA.bs, findingFor(a), #endOfDay) == null or AlertCore.known(eA.bs.alerts, findingFor(a)) == null) };
};
// finish the run
label rest loop { switch (eA.tryAdvance(4)) { case (#ok(_)) {}; case (#err(_)) break rest } };
let countsA = AlertCore.counts(eA.bs.alerts);
var flaggedAccounts = 0;
for (a in ProductCore.accountIds(eA.bs.product).vals()) {
  switch (ProductCore.bookOf(eA.bs.product, a)) { case (?b) { if (Text.equal(b, "BR01") and flagged(a) and a != wideAccount) flaggedAccounts += 1 }; case null {} };
};
assert (countsA.opened == flaggedAccounts);
assert (countsA.open == flaggedAccounts);
Debug.print("count: alerts opened by the end-of-day job, one per finding = " # Nat.toText(countsA.opened));
// every one known by its key, none twice
for (a in ProductCore.accountIds(eA.bs.product).vals()) {
  if (flagged(a) and a != wideAccount) {
    switch (ProductCore.bookOf(eA.bs.product, a)) {
      case (?b) { if (Text.equal(b, "BR01")) { assert (AlertCore.known(eA.bs.alerts, findingFor(a)) != null); assert (Core.alertFor(eA.bs, findingFor(a), #endOfDay) == null) } };
      case null {};
    };
  };
};
// the refusal is a recorded failure of the item, naming the account and the bound
let runA = runOf(eA);
var refusedFailures = 0;
for (f in List.values(runA.failures)) { if (f.job == #monitoring and Text.equal(f.entity, Nat.toText(wideAccount)) and Text.contains(f.error, #text "TooWide")) refusedFailures += 1 };
assert (refusedFailures == 1);
Debug.print("count: evaluations refused for their bound and recorded as failures = " # Nat.toText(refusedFailures));

// the review: rebuilt from the row and the block, cleared or escalated once, under the command path
let ab = Core.alertBlocks(eA.bb);
let firstAlert = AlertCore.listOpenPaged(eA.bs.alerts, ab, null, 1).rows[0];
assert (firstAlert.status == #open and firstAlert.source == #endOfDay and Text.equal(firstAlert.finding.rule, "velocity-1"));
let secondA = AlertCore.listOpenPaged(eA.bs.alerts, ab, ?(firstAlert.id + 1), 1).rows[0];
eA.refuse(#clearAlert({ alert = 9_999_999; reason = "no such alert" }), "UnknownAlert");
eA.refuse(#clearAlert({ alert = firstAlert.id; reason = "" }), "InvalidReview");
ignore eA.cmd(#clearAlert({ alert = firstAlert.id; reason = "the customer's documented payroll" }));
eA.refuse(#clearAlert({ alert = firstAlert.id; reason = "again" }), "AlertNotOpen");
eA.refuse(#escalateAlert({ alert = firstAlert.id; reportRef = "STR-1" }), "AlertNotOpen");
ignore eA.cmd(#escalateAlert({ alert = secondA.id; reportRef = "STR-2026-000017" }));
switch (AlertCore.get(eA.bs.alerts, ab, firstAlert.id)) {
  case (?a) { switch (a.status) { case (#cleared(c)) assert (Text.equal(c.reason, "the customer's documented payroll") and c.at > firstAlert.id); case (_) assert false } };
  case null assert false;
};
switch (AlertCore.get(eA.bs.alerts, ab, secondA.id)) {
  case (?a) { switch (a.status) { case (#escalated(e)) assert (Text.equal(e.reportRef, "STR-2026-000017")); case (_) assert false } };
  case null assert false;
};
let afterA = AlertCore.counts(eA.bs.alerts);
assert (afterA.cleared == 1 and afterA.escalated == 1 and afterA.open == countsA.open - 2);
// the open set skips what was resolved; the account's alerts still list them
var openSeen = 0;
var cursorA : ?Nat = null;
label pg loop {
  let page = AlertCore.listOpenPaged(eA.bs.alerts, ab, cursorA, 3);
  for (a in page.rows.vals()) { assert (a.status == #open); openSeen += 1 };
  switch (page.cursor) { case null break pg; case (?c) cursorA := ?c };
};
assert (openSeen == afterA.open);
assert (AlertCore.alertsOfAccount(eA.bs.alerts, ab, firstAlert.finding.account, 10).size() == 1);
// the review is dual: both commands are behind a dual-by-default permission
for (c in ([#clearAlert({ alert = 1; reason = "x" }), #escalateAlert({ alert = 1; reportRef = "x" })] : [T.Command]).vals()) {
  switch (P.forCommand(c)) { case (?perm) assert (perm.dualByDefault); case null assert false };
};
// and the fold is the log's: a replay agrees
let replayedA = Core.replay(installer, BankMemLog.blocks(eA.bchain));
assert (Core.fingerprint(replayedA) == Core.fingerprint(eA.bs));
Debug.print("count: alerts reviewed under dual control = 2");
Debug.print("count: open alerts walked by cursor after the review = " # Nat.toText(openSeen));
monitorHook := Core.noMonitor;

Debug.print("END OF DAY TEST GREEN");
