#!/usr/bin/env python3
"""kat_to_motoko.py; the NIST/pq-crystals ML-DSA-44 known-answer vectors (kat_mldsa44.rsp: pk, msg, ctx,
sm = signature ‖ message) as a Motoko module of byte arrays, for test/MlDsa44.test.mo.

Usage: kat_to_motoko.py [--count 6] [--out test/support/MlDsa44Kat.mo]
"""
import argparse
import os


def parse(path):
    vecs, cur = [], {}
    for line in open(path):
        line = line.strip()
        if not line:
            continue
        k, _, v = line.partition(" = ")
        if k == "count" and cur:
            vecs.append(cur); cur = {}
        cur[k] = v
    if cur:
        vecs.append(cur)
    return vecs


def mo_bytes(hexs):
    b = bytes.fromhex(hexs)
    return "[" + ", ".join(str(x) for x in b) + "]"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--kat", default=os.path.join(os.path.dirname(__file__), "kat_mldsa44.rsp"))
    ap.add_argument("--count", type=int, default=6)
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "..", "test", "support", "MlDsa44Kat.mo"))
    a = ap.parse_args()
    vecs = parse(a.kat)[: a.count]
    out = ["/// MlDsa44Kat.mo; GENERATED by tools/pq/kat_to_motoko.py from the ML-DSA-44 known-answer file", "/// (tools/pq/kat_mldsa44.rsp): public key, context, message and signature of the first vectors.", "", "module {", "  public type Vector = { count : Nat; pk : [Nat8]; ctx : [Nat8]; msg : [Nat8]; sig : [Nat8] };", "  public let VECTORS : [Vector] = ["]
    for v in vecs:
        mlen = int(v["mlen"])
        sm = bytes.fromhex(v["sm"])
        sig, msg = sm[:-mlen], sm[-mlen:]
        assert msg.hex() == v["msg"] and len(sig) == 2420, (v["count"], len(sig))
        out.append(f"    {{ count = {v['count']}; pk = {mo_bytes(v['pk'])}; ctx = {mo_bytes(v['ctx'])}; msg = {mo_bytes(v['msg'])}; sig = {mo_bytes(sig.hex())} }},")
    out += ["  ];", "}", ""]
    open(a.out, "w").write("\n".join(out))
    print(f"wrote {a.out}: {len(vecs)} vectors")


if __name__ == "__main__":
    main()
