#!/usr/bin/env python3
"""Generate test/TreasuryVectors.mo: the Python twin's figures for the treasury arithmetic (treasury).

`integration/treasury_twin.py` follows `src/bank/TreasuryMath.mo` step for step; this tool runs it over a
deterministic set of inputs — curves, forwards, money-market deposits, bonds under four day counts, swaps,
options across moneyness and tenor — and writes the results as Motoko constants, so `test/TreasuryMath.test.mo`
proves the contract's arithmetic equals the twin's without a replica. The set is seeded, not hand-picked; the
figures are what the twin computed, not what anyone expected.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "integration"))
import treasury_twin as T  # noqa: E402

from fractions import Fraction  # noqa: E402

rng = random.Random(20260913)

CONV_CODES = {"A001": "#a001_ActActIcma({ couponsPerYear = %d })", "A003": "#a003_Act360", "A004": "#a004_Act365Fixed",
              "A005": "#a005_ActActIsda", "A006": "#a006_Thirty360Isda", "A007": "#a007_ThirtyE360", "A011": "#a011_Thirty365"}


def conv_mo(code, cpy):
    s = CONV_CODES[code]
    return s % cpy if "%d" in s else s


def points_mo(points):
    return "[" + ", ".join("(%d, %d)" % (t, v) for t, v in points) + "]"


def curve(n, lo, hi, tenors=(1, 7, 30, 90, 180, 365, 730, 1825), r=None):
    pts = []
    for t in tenors[:n]:
        pts.append((t, (r or rng).randint(lo, hi)))
    return pts


# The forty-pillar grid the raised cap admits (S4.1, the treasury review): overnight to thirty years.
TENORS_40 = (1, 2, 7, 14, 21, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 365, 456, 548, 639, 730, 912, 1095,
             1278, 1460, 1825, 2190, 2555, 2920, 3285, 3650, 4380, 5110, 5840, 6570, 7300, 8030, 8760, 9490, 10950)
assert len(TENORS_40) == 40
rng2 = random.Random(20260913 + 41)   # the extended vectors draw from their own stream, so the first set is unchanged


D0 = T.from_civil(2026, 9, 14)

out = []
out.append("// GENERATED by tools/gen_treasury_vectors.py from integration/treasury_twin.py. Do not edit.")
out.append("// Attribution: Thebes Core Team. Licence: Apache 2.0.")
out.append("import DC \"../src/bank/DayCount\";")
out.append("module {")

# 1. interpolation and discounting
rows = []
for _ in range(24):
    pts = curve(rng.randint(1, 8), 100, 2500)
    tenor = rng.randint(0, 2000)
    v = T.interpolate(pts, tenor)
    df = T.discount_on(pts, tenor)
    # (points, tenor, valueNum, valueDen, dfNum, dfDen)
    rows.append("(%s, %d, %d, %d, %d, %d)" % (points_mo(pts), tenor, v.numerator, v.denominator, df.numerator, df.denominator))
# the forty-pillar curves: every pillar count from 17 to 40, tenors across the whole grid and past its end
for n in range(17, 41):
    pts = curve(n, 100, 2500, tenors=TENORS_40, r=rng2)
    tenor = rng2.randint(0, 12000)
    v = T.interpolate(pts, tenor)
    df = T.discount_on(pts, tenor)
    rows.append("(%s, %d, %d, %d, %d, %d)" % (points_mo(pts), tenor, v.numerator, v.denominator, df.numerator, df.denominator))
out.append("  /// (zero curve, tenor, interpolated n, d, discount factor n, d)")
out.append("  public let CURVES : [([(Nat, Int)], Nat, Int, Nat, Int, Nat)] = [\n    " + ",\n    ".join(rows) + "\n  ];")

# 2. forwards
rows = []
for _ in range(32):
    buy = rng.random() < 0.5
    base = rng.randint(1_000_00, 5_000_000_00)
    spot_num, spot_den = rng.randint(4_500_000_000, 5_200_000_000), 100_000_000   # ratio of minor units (2 dp both) with 8 dp precision
    spot = T.rate_micro(spot_num, spot_den)
    fwd_pts = [(t, rng.randint(-200_000, 900_000)) for t in (7, 30, 90, 180, 365)]
    zero = curve(6, 1500, 2600)
    deal_rate = int(spot) + rng.randint(-300_000, 800_000)
    days = rng.randint(0, 400)
    mark = T.forward_mark(buy, base, deal_rate, spot, fwd_pts, zero, days)
    realised = T.forward_realised(buy, base, deal_rate, spot)
    qa = T.quote_amount(base, deal_rate)
    rows.append("(%s, %d, %d, %d, %d, %s, %s, %d, %d, %d, %d)" % ("true" if buy else "false", base, deal_rate, spot_num, spot_den,
                points_mo(fwd_pts), points_mo(zero), days, mark, realised, qa))
out.append("  /// (buyBase, baseAmount, dealRateMicro, spotNum, spotDen, forwardPoints, quoteZero, remainingDays, mark, realised, quoteAmount)")
out.append("  public let FORWARDS : [(Bool, Nat, Nat, Nat, Nat, [(Nat, Int)], [(Nat, Int)], Nat, Int, Int, Nat)] = [\n    " + ",\n    ".join(rows) + "\n  ];")

# 3. money market
rows = []
for _ in range(24):
    conv = rng.choice(["A003", "A004", "A005", "A006", "A007", "A011"])
    principal = rng.randint(100_000_00, 50_000_000_00)
    rate = rng.randint(50, 3000)
    start = D0 + rng.randint(0, 60)
    day = start + rng.randint(0, 400)
    rows.append("(%s, %d, %d, %d, %d, %d)" % (conv_mo(conv, 1), principal, rate, start, day, T.simple_interest_to(principal, rate, conv, start, day)))
out.append("  /// (convention, principal, rateBps, start, day, cumulative interest)")
out.append("  public let MONEY_MARKET : [(DC.Convention, Nat, Nat, Nat, Nat, Nat)] = [\n    " + ",\n    ".join(rows) + "\n  ];")

# 4. bonds: periods, accrued, clean cost, yield, amortisation schedule
rows = []
for _ in range(16):
    cpy = rng.choice([1, 2, 4, 12])
    conv = rng.choice(["A001", "A003", "A006", "A007", "A005"])
    nominal = rng.randint(1, 50) * 100_000_00
    coupon = rng.randint(200, 1800)
    issue = D0 - rng.randint(0, 700)
    years = rng.randint(1, 7)
    maturity = T.add_months(issue, 12 * years)
    periods = T.coupon_periods(nominal, coupon, cpy, conv, issue, maturity)
    settlement = D0 + rng.randint(0, 20)
    while settlement >= maturity:
        settlement -= 30
    if settlement < issue:
        settlement = issue
    price = rng.randint(92_000_000, 108_000_000)
    clean = T.clean_cost(nominal, price)
    accrued = T.accrued_coupon(nominal, coupon, conv, periods, settlement, cpy)
    y = T.effective_yield_millionths(nominal, periods, conv, cpy, settlement, clean + accrued)
    sched = T.amortisation_schedule(nominal, periods, conv, cpy, settlement, clean, y)
    probe_day = settlement + rng.randint(0, 200)
    amort_probe = 0
    for st in sched:
        if st["start"] <= probe_day < st["end"]:
            amort_probe = T.amortisation_to(st, probe_day)
    sched_mo = "[" + ", ".join("(%d, %d, %d, %d, %d, %d)" % (s["start"], s["end"], s["interest"], s["couponPart"], s["amortisation"], s["carryingEnd"]) for s in sched) + "]"
    per_mo = "[" + ", ".join("(%d, %d, %d)" % (p["start"], p["end"], p["amount"]) for p in periods) + "]"
    rows.append("(%s, %d, %d, %d, %d, %d, %s, %d, %d, %d, %d, %d, %s, %d, %d)" % (conv_mo(conv, cpy), cpy, nominal, coupon, issue, maturity, per_mo,
                settlement, price, clean, accrued, y, sched_mo, probe_day, amort_probe))
out.append("  /// (convention, couponsPerYear, nominal, couponBps, issue, maturity, periods (start, end, amount), settlement, priceMicro, cleanCost, accrued, yieldMillionths, schedule (start, end, interest, couponPart, amortisation, carryingEnd), probeDay, amortisationAtProbe)")
out.append("  public let BONDS : [(DC.Convention, Nat, Nat, Nat, Nat, Nat, [(Nat, Nat, Nat)], Nat, Nat, Nat, Nat, Nat, [(Nat, Nat, Nat, Nat, Int, Nat)], Nat, Int)] = [\n    " + ",\n    ".join(rows) + "\n  ];")

# 5. swaps
rows = []
for _ in range(16):
    conv = rng.choice(["A003", "A004", "A006"])
    notional = rng.randint(1, 100) * 1_000_000_00
    pay_fixed = rng.random() < 0.5
    fixed = rng.randint(800, 2500)
    spread = rng.randint(-50, 150)
    months = rng.choice([3, 6, 12])
    start = D0 - rng.randint(0, 300)
    maturity = T.add_months(start, months * rng.randint(2, 12))
    periods = T.swap_periods(start, maturity, months)
    zero = curve(8, 1200, 2600)
    day = D0 + rng.randint(0, 100)
    fixings = {}
    for p in periods:
        if p["start"] <= day and rng.random() < 0.8:
            fixings[p["start"]] = rng.randint(900, 2400)
    mark = T.swap_mark(notional, pay_fixed, fixed, spread, conv, periods, zero, day, lambda s: fixings.get(s))
    per_mo = "[" + ", ".join("(%d, %d)" % (p["start"], p["end"]) for p in periods) + "]"
    fix_mo = "[" + ", ".join("(%d, %d)" % (k, v) for k, v in sorted(fixings.items())) + "]"
    rows.append("(%s, %d, %s, %d, %d, %s, %s, %d, %s, %d)" % (conv_mo(conv, 1), notional, "true" if pay_fixed else "false", fixed, spread, per_mo, points_mo(zero), day, fix_mo, mark))
# the long swaps the raised cap admits: quarterly to thirty and thirty-two years (120 and 128 periods), semi-annual to
# thirty, on forty-pillar curves, with fixings recorded on the periods already started
for months, years in ((3, 30), (3, 32), (6, 30), (3, 25)):
    conv = rng2.choice(["A003", "A004", "A006"])
    notional = rng2.randint(1, 100) * 1_000_000_00
    pay_fixed = rng2.random() < 0.5
    fixed = rng2.randint(800, 2500)
    spread = rng2.randint(-50, 150)
    start = D0 - rng2.randint(0, 3000)
    maturity = T.add_months(start, 12 * years)
    periods = T.swap_periods(start, maturity, months)
    assert len(periods) == 12 * years // months, len(periods)
    zero = curve(40, 1200, 2600, tenors=TENORS_40, r=rng2)
    day = D0 + rng2.randint(0, 100)
    fixings = {}
    for p in periods:
        if p["start"] <= day and rng2.random() < 0.8:
            fixings[p["start"]] = rng2.randint(900, 2400)
    mark = T.swap_mark(notional, pay_fixed, fixed, spread, conv, periods, zero, day, lambda s: fixings.get(s))
    per_mo = "[" + ", ".join("(%d, %d)" % (p["start"], p["end"]) for p in periods) + "]"
    fix_mo = "[" + ", ".join("(%d, %d)" % (k, v) for k, v in sorted(fixings.items())) + "]"
    rows.append("(%s, %d, %s, %d, %d, %s, %s, %d, %s, %d)" % (conv_mo(conv, 1), notional, "true" if pay_fixed else "false", fixed, spread, per_mo, points_mo(zero), day, fix_mo, mark))
out.append("  /// (convention, notional, payFixed, fixedBps, spreadBps, periods, zero curve, day, fixings (periodStart, bps), mark)")
out.append("  public let SWAPS : [(DC.Convention, Nat, Bool, Nat, Int, [(Nat, Nat)], [(Nat, Int)], Nat, [(Nat, Nat)], Int)] = [\n    " + ",\n    ".join(rows) + "\n  ];")

# 6. fixed point primitives and options
rows = []
for _ in range(24):
    x = rng.randint(-40 * T.ONE, 5 * T.ONE)
    rows.append("(%d, %d)" % (x, T.fexp(x)))
out.append("  public let EXP : [(Int, Int)] = [\n    " + ",\n    ".join(rows) + "\n  ];")
rows = []
for _ in range(24):
    x = rng.randint(1, 50 * T.ONE)
    rows.append("(%d, %d)" % (x, T.fln(x)))
out.append("  public let LN : [(Int, Int)] = [\n    " + ",\n    ".join(rows) + "\n  ];")
rows = []
for _ in range(24):
    x = rng.randint(-6 * T.ONE, 6 * T.ONE)
    rows.append("(%d, %d)" % (x, T.norm_cdf(x)))
out.append("  public let NORM : [(Int, Int)] = [\n    " + ",\n    ".join(rows) + "\n  ];")
rows = []
for _ in range(40):
    call = rng.random() < 0.5
    base = rng.randint(1_000_00, 10_000_000_00)
    spot = rng.randint(40_000_000, 55_000_000)
    strike = spot + rng.randint(-6_000_000, 6_000_000)
    rd, rf = rng.randint(500, 2800), rng.randint(0, 900)
    vol = rng.choice([0, 500, 900, 1500, 2500, 4000])
    days = rng.choice([0, 1, 7, 30, 90, 180, 365, 730])
    rows.append("(%s, %d, %d, %d, %d, %d, %d, %d, %d)" % ("true" if call else "false", base, spot, strike, rd, rf, vol, days,
                T.garman_kohlhagen(call, base, spot, strike, rd, rf, vol, days)))
out.append("  /// (call, baseAmount, spotMicro, strikeMicro, domesticBps, foreignBps, volBps, days, value)")
out.append("  public let OPTIONS : [(Bool, Nat, Int, Nat, Int, Int, Nat, Nat, Nat)] = [\n    " + ",\n    ".join(rows) + "\n  ];")
out.append("}")

path = os.path.join(os.path.dirname(__file__), "..", "test", "TreasuryVectors.mo")
with open(path, "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote", path, "bytes", os.path.getsize(path))
