#!/usr/bin/env python3
"""Generate test/OriginationVectors.mo: WebAuthn ES256 assertion fixtures for the origination tests (origination and underwriting).

The vectors are produced with Python's `cryptography` (OpenSSL) from a fixed private scalar, so the file is
deterministic and the Motoko verifier (`OriginationCore.verifyAssertion`) is checked against an independent
implementation: a valid assertion over a challenge, and the refusals the contract must make; a wrong
challenge, a wrong origin, a wrong relying party, the user-present flag clear, a tampered signature, another
party's key, a ceremony that is not webauthn.get.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import base64
import hashlib
import json
import struct
import sys

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

RP_ID = "bank.example"
ORIGIN = "https://bank.example"

PRIVATE_SCALAR = 0x1D3A7B9E5C2F4A6D8B0E1C3F5A7D9B2E4C6F8A0D2B4E6C8F0A2D4B6E8C0F2A4D
OTHER_SCALAR = 0x7A5C3E1F9B8D6A4C2E0F1D3B5A7C9E8F6D4B2A0C8E6F4D2B0A9C7E5F3D1B8A6C


def b64url(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode()


def mo_blob(b: bytes) -> str:
    return '"' + "".join("\\%02x" % x for x in b) + '"'


def key(scalar: int):
    return ec.derive_private_key(scalar, ec.SECP256R1())


def spki(k) -> bytes:
    return k.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)


def auth_data(rp_id: str, flags: int, counter: int = 7) -> bytes:
    return hashlib.sha256(rp_id.encode()).digest() + bytes([flags]) + struct.pack(">I", counter)


def client_data(challenge: bytes, origin: str = ORIGIN, typ: str = "webauthn.get") -> bytes:
    return json.dumps({"type": typ, "challenge": b64url(challenge), "origin": origin, "crossOrigin": False}, separators=(",", ":")).encode()


def sign(k, authenticator_data: bytes, client_data_json: bytes) -> bytes:
    to_sign = authenticator_data + hashlib.sha256(client_data_json).digest()
    return k.sign(to_sign, ec.ECDSA(hashes.SHA256(), deterministic_signing=True))   # RFC 6979: the file reproduces byte for byte


def main():
    k = key(PRIVATE_SCALAR)
    other = key(OTHER_SCALAR)
    cred = hashlib.sha256(b"credential-1").digest()[:16]
    challenge = hashlib.sha256(b"offer-1").digest()
    wrong_challenge = hashlib.sha256(b"offer-2").digest()

    vectors = []

    def add(name, k_, cred_, ad, cd, sig=None, want=True):
        sig = sig if sig is not None else sign(k_, ad, cd)
        vectors.append((name, cred_, ad, cd, sig, want))

    ad = auth_data(RP_ID, 0x05)
    cd = client_data(challenge)
    add("valid", k, cred, ad, cd, want=True)
    add("wrong challenge", k, cred, ad, client_data(wrong_challenge), want=False)
    add("wrong origin", k, cred, ad, client_data(challenge, origin="https://evil.example"), want=False)
    add("not a get ceremony", k, cred, ad, client_data(challenge, typ="webauthn.create"), want=False)
    add("wrong relying party", k, cred, auth_data("other.example", 0x05), cd, want=False)
    add("user not present", k, cred, auth_data(RP_ID, 0x04), cd, want=False)
    good = sign(k, ad, cd)
    tampered = bytearray(good)
    tampered[-1] ^= 0x01
    add("tampered signature", k, cred, ad, cd, sig=bytes(tampered), want=False)
    add("another party's key", other, cred, ad, cd, want=False)
    unknown_cred = hashlib.sha256(b"credential-9").digest()[:16]
    add("unknown credential", k, unknown_cred, ad, cd, want=False)

    out = []
    out.append("// GENERATED by tools/gen_origination_vectors.py from Python cryptography (OpenSSL). Do not edit.")
    out.append("// Attribution: Thebes Core Team. Licence: Apache 2.0.")
    out.append("module {")
    out.append(f'  public let RP_ID : Text = "{RP_ID}";')
    out.append(f'  public let ORIGIN : Text = "{ORIGIN}";')
    out.append(f"  public let SPKI : Blob = {mo_blob(spki(k))};")
    out.append(f"  public let OTHER_SPKI : Blob = {mo_blob(spki(other))};")
    out.append(f"  public let CREDENTIAL : Blob = {mo_blob(cred)};")
    out.append(f"  public let CHALLENGE : Blob = {mo_blob(challenge)};")
    out.append("  /// (name, credentialId, authenticatorData, clientDataJSON, signature, verifies)")
    out.append("  public let ASSERTIONS : [(Text, Blob, Blob, Blob, Blob, Bool)] = [")
    for name, cred_, ad_, cd_, sig_, want in vectors:
        out.append(f'    ("{name}", {mo_blob(cred_)}, {mo_blob(ad_)}, {mo_blob(cd_)}, {mo_blob(sig_)}, {"true" if want else "false"}),')
    out.append("  ];")
    out.append("}")
    target = sys.argv[1] if len(sys.argv) > 1 else "test/OriginationVectors.mo"
    with open(target, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {target} with {len(vectors)} assertions")


if __name__ == "__main__":
    main()
